import Foundation

/// Auto-generated English → zh-Hans map for Coach bilingual strings.
/// Curated entries from scripts/zh_hans_curated_coach.py take precedence.
enum CoachChineseOverridesTable {
    static let entries: [String: String] = [
        "1 activity": "1. 活动",
        "1 recovery session": "1个恢复会话",
        "1 workout": "1次锻炼",
        "10-minute warmup — \\(title) starts at \\(time).": "10 分钟热身 —\\(title)从\\(time)开始。",
        "10-minute warmup — \\(titleEN) at \\(time).": "10 分钟热身 —\\(titleEN)@\\(time)。",
        "10–15 calm minutes — stopping early is fine.": "10–15分钟平静—提前停下来没问题。",
        "10–20 calm minutes, then water and rest.": "10–20分钟冷静下来，然后浇水休息。",
        "15-minute warmup — \\(titleEN) at \\(time).": "15 分钟热身 —\\(titleEN)@\\(time)。",
        "15–20 easy minutes — slower pace than usual.": "15–20分钟—比平时慢。",
        "A few days": "这几天",
        "A full day of training — now it's about landing softly.": "一整天的培训—现在是关于轻轻着陆。",
        "A gentle option — only if it fits today.": "一个温和的选择—只有当它适合今天。",
        "A hard workout today is likely to add fatigue instead of fitness.": "今天的艰苦锻炼可能会增加疲劳而不是健身。",
        "A lighter day can be reasonable given today’s signals. Confirm if you want a Plan suggestion — Coach won’t change your Plan without that review.": "考虑到今天的信号，更轻松的一天可能是合理的。确认您是否需要计划建议—如果没有该审查，培训讲师将不会更改您的计划。",
        "A long ride needs freshness, fluids, and energy before it starts. The evening before matters more than doing extra work today.": "长途骑行在开始之前需要新鲜感、液体和能量。前一天晚上比今天做额外的工作更重要。",
        "A normal meal now supports steady energy without changing the whole plan.": "正常饮食现在可以在不改变整个计划的情况下支持稳定的能量。",
        "A quick look back at \\(title.english.lowercased()).": "快速回顾一下\\ (title.english.lowercased ())。",
        "A quieter day now will help you return stronger tomorrow.": "现在更安静的一天将帮助你明天恢复更强大。",
        "A real meal is better than random snacking": "真正的一餐比随机零食要好",
        "A short chat about today’s sleep, training, and food.": "用简短对话了解今天的睡眠、训练和饮食。",
        "A slightly earlier wind-down tonight is a gentle option — no need for another workout.": "今晚稍微早一点放松是一个温和的选择—无需再次锻炼。",
        "A walk is next — let the morning settle first.": "接下来是散步—让早晨先安顿下来。",
        "About \\(hoursEN) hike — real time on your feet, so prep matters.": "关于\\(hoursEN)徒步——全程实地体验，充分准备至关重要。",
        "About \\(hoursEN) on trail — treat this as a full outing, not a stroll.": "关于\\(hoursEN)的徒步路线——请将此视为一次完整的徒步之旅，而非简单的散步。",
        "Activity": "活动",
        "Activity volume looked similar to \\(previousPhrase.english).": "活动量与\\ (previousPhrase.english)相似。",
        "After HIIT": "HIIT后",
        "After a heavy day — this walk is about settling down.": "忙碌了一天后，这次散步是为了安顿下来。",
        "After harder sessions, your recovery tends to be better when you get enough protein afterward. You're still short of the range that usually works for you.": "在经历了更艰难的疗程后，当您之后摄入足够的蛋白质时，您的恢复往往会更好。您仍未达到通常适用的范围。",
        "After heat": "加热后",
        "After lifting": "起吊后",
        "After sauna": "桑拿后",
        "After session": "看诊之后",
        "After the match": "比赛结束后",
        "After the ride": "行程结束后",
        "After the run": "运行后",
        "After the swim": "游泳后",
        "After this set — decide whether to trim the rest.": "在此集合之后—决定是否修剪其余部分。",
        "After yesterday's load — don't force it today.": "在昨天的负荷之后—今天不要强迫它。",
        "Aim for similar bed and wake times on the nights you can measure.": "在您可以测量的夜晚，设定类似的床位和起床时间。",
        "Anchor one priority block before noon.": "在中午之前锚定一个优先级块。",
        "Another \\(minutesPhrase(remaining)) easy minutes is enough.": "再轻松地练\\(minutesPhrase(remaining))分钟就够了。",
        "Another \\(minutesPhrase(remaining)) soft minutes is enough.": "再轻柔地练\\(minutesPhrase(remaining))分钟就够了。",
        "Another check-in. How’s energy right now?": "再确认一下。现在精力如何？",
        "Another option": "添加另一个选项",
        "Any preference for the suggestion?": "您对建议有什么偏好吗？",
        "App recovery reading \\(recovery)% is below your usual ~\\(baseline)%, while you feel okay — we’ll note the gap without overriding how you feel.": "App 恢复读数\\(recovery)% 低于您平时的 ~\\(baseline)%，但您仍感觉良好——我们会记录这一差异，但不会因此改变您的主观感受。",
        "Arrive on the mat and take one soft breath before the first pose.": "到达垫子上，在第一次姿势前轻轻吸一口气。",
        "Arrive soft — no pressure in the first poses.": "到达柔软—第一个姿势没有压力。",
        "Ask Coach only uses completed sessions and measured recovery signals — nothing is invented.": "Ask Coach仅使用已完成的会话和测量的恢复信号—没有任何发明。",
        "Ask another question": "其他问题",
        "Average overnight HRV \\(Int(avgHRV.rounded())) ms": "平均过夜HRV\\ (Int (avgHRV.rounded ())) ms",
        "Average overnight resting HR \\(Int(avgRHR.rounded())) bpm": "平均过夜静息心率\\ (Int (avgRHR.rounded ())) bpm",
        "Average recorded sleep was \\(sleepText.english).": "记录的平均睡眠为\\ (sleepText.english)。",
        "Average recovery \\(rounded)%": "平均回收率\\ （四舍五入） %",
        "Average recovery score \\(average)% — about \\(abs(delta)) points lower than before.": "平均恢复评分\\(average)% ——较此前降低约\\(abs(delta)分。",
        "Average recovery score \\(average)% — about \\(delta) points higher than before.": "平均恢复评分\\(average)% —— 较之前提高约\\(delta)个百分点。",
        "Average recovery score \\(average)% — similar to before.": "平均回收率\\(average)% —— 与之前相当。",
        "Average recovery score \\(rounded)% on days with data.": "有数据天数的平均恢复分数\\ （四舍五入） %。",
        "Average recovery score was lower than before where data exists.": "在存在数据的情况下，平均恢复分数低于之前。",
        "Average sleep \\(sleep.english)": "平均睡眠\\ (sleep.english)",
        "Average sleep \\(sleepText.english)": "平均睡眠\\ (sleepText.english)",
        "Average sleep: \\(curText.english) vs \\(prevText.english).": "平均睡眠：\\ (curText.english) vs\\ (prevText.english)。",
        "Be Careful With": "小心",
        "Be ready around \\(time) for \\(title).": "在\\ (TITLE)的\\ (TIME)左右做好准备。",
        "Before HIIT": "HIIT 前",
        "Before breath work": "呼吸工作前",
        "Before lifting": "起吊前",
        "Before recovery": "恢复前",
        "Before sauna": "桑拿房前",
        "Before session": "疗程前",
        "Before stretching": "拉伸前",
        "Before the match": "比赛前",
        "Before the next set — two breaths, brace, go.": "在下一组之前—两次呼吸，支撑，开始。",
        "Before the ride": "骑行前",
        "Before the run": "跑步前",
        "Before the session": "训练前",
        "Before the swim": "游泳前",
        "Before the walk": "散步前",
        "Before yoga": "练习瑜伽之前",
        "Better to finish fresh than chase volume": "比追逐卷更好地完成新鲜",
        "Big endurance day — evening is for landing softly.": "大耐力日—晚上是轻柔着陆的日子。",
        "Big ride day — evening is for landing softly.": "大型骑行日—傍晚是轻柔着陆的日子。",
        "Big run day — evening is for landing softly.": "大型跑步日—傍晚是轻柔着陆的日子。",
        "Big swim day — evening is for landing softly.": "大型游泳日—晚上是轻柔着陆的日子。",
        "Breath day is closing — protect the calm tonight.": "呼吸日即将结束—保护今晚的平静。",
        "Breath work ahead": "提前做好呼吸工作",
        "Breath work finished — keep the quiet.": "呼吸工作完成—保持安静。",
        "Breath work is ahead — quiet room, open chest.": "呼吸工作在前面—安静的房间，打开胸部。",
        "Breath work is done — carry the ease forward.": "呼吸工作已经完成—将轻松向前推进。",
        "Breath work is live — quiet and unhurried.": "呼吸工作是现场直播—安静且不慌不忙。",
        "Breath work is live — quiet, soft, and unhurried.": "呼吸工作是现场直播—安静、柔和、不着急。",
        "Breathe out on the swing — reset between points.": "在秋千上呼气—在点之间重置。",
        "Bring fluids back up": "带回液体",
        "Bring more water than feels necessary.": "携带的水量超过必要的水量。",
        "Bring water, a snack, and blister care, and start easier than the trail invites.": "带上水、零食和泡沫护理，比徒步旅行更轻松地开始。",
        "Calories are \\(calLogged) of \\(calGoal) kcal — about \\(nutrition.caloriesRemaining) kcal left.": "剩余热量为\\(calLogged)×\\(calGoal)kcal —— 约剩\\(nutrition.caloriesRemaining)kcal。",
        "Calories are \\(calLogged) of \\(calGoal) kcal — close to your target.": "卡路里为\\(calLogged)×\\(calGoal)kcal —— 接近您的目标值。",
        "Calories are about \\(Int((-delta).rounded())) kcal over today’s \\(calGoal) kcal goal.": "每日所需热量约为\\(Int((-delta).rounded() kcal，相对于当前\\(calGoal)kcal 的目标值。",
        "Calories lag today's load.": "热量落后于今天的负荷。",
        "Changed plans": "计划有变",
        "Check breathing in five minutes — downshift if it's labored.": "在五分钟内检查呼吸—如果工作繁重，则缩短班次。",
        "Check food log": "检查食物日志",
        "Check legs and breathing in ten minutes.": "十分钟后检查腿和呼吸。",
        "Check legs and sleep once more before you begin.": "开始前再检查一下腿和睡眠。",
        "Check readiness": "检查准备情况",
        "Check readiness first": "先检查准备情况",
        "Check shoes, socks, and a simple blister fix.": "检查鞋子，袜子和一个简单的水泡修复。",
        "Check shoes, water, and start easier than you think.": "检查鞋子，水，并开始比你想象的更容易。",
        "Check water and cadence over the next ten minutes.": "在接下来的十分钟内检查水和节奏。",
        "Choose a bedtime and start winding down.": "选择一个睡觉时间，开始放松。",
        "Choose an easy walk, gentle stretching, or simply give yourself more time to recover.": "选择轻松的散步，轻柔的伸展运动，或者只是给自己更多的时间来恢复。",
        "Choose whichever fits — there’s no wrong answer.": "选择适合的-没有错误的答案。",
        "Clean reps over load.": "清洁重载代表。",
        "Coach": "教练",
        "Come back under \\(cap) and walk at a comfortable pace.": "把心率降回\\(cap)以下，用舒适的步速走。",
        "Comfortable": "舒适",
        "Compared with \\(previousNoun.english), your average score moved by \\(delta) points on recorded days.": "与 \\ (上一个名词。英语) 相比，您的平均得分在记录的天数上移动了 \\(delta) 点。",
        "Comparison with the previous \\(input.period.dayCount) days.": "与前 \\(input.period.dayCount) 天的比较。",
        "Completed sessions clustered on relatively few days this period.": "在此期间，完成的会话聚集在相对较少的几天内。",
        "Connect Apple Health to analyze workouts, sleep, and recovery from your data.": "连接Apple Health，从数据中分析锻炼、睡眠和恢复情况。",
        "Control the session": "控制会话",
        "Control today's ride": "控制今天的骑行",
        "Control today's run": "控制今天的跑步",
        "Control today's squash session": "控制今天的壁球会议",
        "Control today's tennis session": "控制今天的网球比赛",
        "Control today's upper body session": "控制今天的上半身会话",
        "Control today's workout": "控制今天的锻炼",
        "Cool down slowly.": "慢慢冷却。",
        "Cool rinse if you like, then step in gently.": "冷却冲洗，如果你喜欢，然后轻轻介入。",
        "Cooldown first, then refuel.": "先冷却，然后加油。",
        "Cooldown on court — then water and stretch.": "球场上的冷却时间-然后水和伸展。",
        "Core block is next — brace before you load.": "加载之前，核心块是下一个支撑。",
        "Core block is next — recovery isn't fully back yet.": "核心块是下一个-恢复还没有完全恢复。",
        "Core work is live — brace and breathe through every rep.": "核心工作是活的-支撑和呼吸通过每个代表。",
        "Court work is done — muscles need quiet now.": "法庭工作已经完成-肌肉现在需要安静。",
        "Cut a set or two now — finishing strong beats finishing wrecked.": "剪掉一组或两组现在结束的强劲节拍，结束被破坏了。",
        "Cut volume early — quality beats quantity on tired days.": "在疲惫的日子里，尽早减少数量-质量胜过数量。",
        "Day's end": "一天的结束",
        "Days without a logged session aren’t labeled as inactivity — only completed sessions count.": "没有记录会话的天数不会标记为仅不活动已完成会话计数。",
        "Demanding": "要求高",
        "Did this start today, or has it lasted a few days?": "这是从今天开始的，还是持续了几天？",
        "Dim lights and start your bedtime routine.": "昏暗的灯光，开始你的睡前程序。",
        "Do not add anything new tonight. Let the body move toward sleep.": "今晚不要添加任何新内容。让身体走向睡眠。",
        "Do not add intensity tonight — it can take capacity away from tomorrow's ride.": "今晚不要增加强度-它可能会减少明天的骑行能力。",
        "Do not force another walk just to chase the activity ring.": "不要强迫另一次步行只是为了追逐活动环。",
        "Do not force extra steps just to chase numbers.": "不要强迫额外的步骤只是为了追逐数字。",
        "Do not force steps just to close a number.": "不要强制步骤只是为了关闭一个数字。",
        "Do not increase load or pace if technique starts to break down.": "如果技术开始崩溃，不要增加负荷或速度。",
        "Do not turn the walk into a fast march or an errands sprint.": "不要把步行变成快速行军或差事冲刺。",
        "Do not turn this run into extra training load.": "不要把这次跑步变成额外的训练负荷。",
        "Does this feel new today, or has it been building?": "这是今天的新感觉，还是它正在建设中？",
        "Don't add another hard block today.": "今天不要添加另一个硬块。",
        "Don't add surges you'll pay for later in the session.": "不要添加您将在稍后的会话中支付的浪涌。",
        "Don't borrow effort from tomorrow to fill today.": "不要从明天借力来填补今天。",
        "Don't chase PRs on a depleted day.": "不要在耗尽的一天追逐PRs。",
        "Don't chase deeper poses or compare to yesterday.": "不要追逐更深的姿势或与昨天相比。",
        "Don't chase depth or compare to yesterday.": "不要追逐深度或与昨天相比。",
        "Don't chase every ball at full stretch.": "不要全力以赴地追逐每一个球。",
        "Don't chase max loads before the body feels awake.": "在身体感觉清醒之前，不要追逐最大负荷。",
        "Don't chase pace just because the legs feel warm.": "不要仅仅因为腿感到温暖就追逐步伐。",
        "Don't chase pace or power — cut it short if needed.": "不要追逐速度或功率-如果需要，请缩短它。",
        "Don't chase pace you can't sustain.": "不要追逐你无法维持的步伐。",
        "Don't chase steps or calories for the numbers alone.": "不要仅仅为了数字而追逐步数或卡路里。",
        "Don't chase the summit if legs or water are already fading.": "如果腿或水已经褪色，不要追逐山顶。",
        "Don't chase yesterday's numbers or stack hard blocks early.": "不要追逐昨天的数字或早期堆栈硬块。",
        "Don't commit to the full plan before you feel the legs.": "在你感觉到腿之前，不要承诺完整的计划。",
        "Don't enter right after heavy food or when overheated.": "不要在食物过重或过热后立即进入。",
        "Don't force deep breaths or hold if it feels strained.": "不要强迫深呼吸或保持，如果感觉紧张。",
        "Don't force every interval to max when recovery is still behind.": "当恢复仍然落后时，不要强迫每个间隔达到最大值。",
        "Don't force intensity or chase a training feel.": "不要强迫强度或追逐训练的感觉。",
        "Don't force speed on tired feet.": "不要在疲惫的脚上强迫速度。",
        "Don't force the full \\(durationEN) effort from the first minutes.": "不要从第一分钟开始就全力以赴。",
        "Don't force the full plan or race the clock from the start.": "不要强迫完整的计划或从一开始就争分夺秒。",
        "Don't force the full program if joints feel stiff.": "如果关节感觉僵硬，不要强制执行完整的程序。",
        "Don't go all-out in the first rally.": "不要在第一次集会中全力不赴。",
        "Don't jump into another intense session later today.": "今天晚些时候不要再紧张了。",
        "Don't jump into another intense session tonight.": "今晚不要再紧张了。",
        "Don't jump into cold shower or hard work right away.": "不要马上洗冷水澡或做艰苦的工作。",
        "Don't jump into the next set while you're still gasping.": "不要在你还在喘气的时候跳到下一组。",
        "Don't jump straight into noise or hard tasks.": "不要直接跳到噪音或艰巨的任务中。",
        "Don't leave hungry, under-watered, or without a turnaround plan.": "不要饿着肚子，浇水不足或没有周转计划。",
        "Don't load max weight on cold muscles.": "不要在冰冷的肌肉上加载最大重量。",
        "Don't match yesterday's pace from the first hour.": "从第一个小时开始就不要匹配昨天的速度。",
        "Don't open at yesterday's pace or planned power.": "不要以昨天的速度或计划的力量打开。",
        "Don't open with a sprint from the first minutes.": "不要从第一分钟开始冲刺。",
        "Don't open with a sprint or heavy gear.": "不要用冲刺或沉重的装备打开。",
        "Don't open with an all-out interval — earn the intensity.": "不要以完全间隔的方式打开-获得强度。",
        "Don't open with explosive rallies.": "不要以爆炸性集会开张。",
        "Don't open with full intensity — the tank isn't full yet.": "不要全速打开 -- 油箱还没装满。",
        "Don't pick up pace or chase extra distance.": "不要加快速度或追逐额外的距离。",
        "Don't pick up pace or take calls that rev you up.": "不要加快步伐，也不要接听让你提速的电话。",
        "Don't pick up pace or treat it like cardio.": "不要加快步伐或将其视为有氧运动。",
        "Don't pile on another heavy session later today.": "今天晚些时候不要再进行繁重的会议了。",
        "Don't pile on another heavy session tonight.": "今晚不要再重重地开会了。",
        "Don't push depth or hold through pain.": "不要通过疼痛来推动深度或保持。",
        "Don't push into pain or bounce through the hold.": "不要陷入痛苦或弹跳。",
        "Don't push the pattern — return to an easy natural breath.": "不要推动模式-恢复轻松自然的呼吸。",
        "Don't push through — ease until it feels calm again.": "不要推过去 -- 放松，直到它再次感到平静。",
        "Don't race the clock from the first set.": "不要从第一盘开始比赛。",
        "Don't race the first climb or save all food for the end.": "不要参加第一次攀登的比赛，也不要把所有的食物都留到最后。",
        "Don't rush back into stress or heavy training.": "不要急于回到压力或繁重的训练中。",
        "Don't rush sets or chase numbers with bad form.": "不要急于集合或追逐形式不好的数字。",
        "Don't rush the first half or ignore sore spots.": "不要急于上半场或忽视痛处。",
        "Don't sit down and replay the match in your head.": "不要坐下来在脑子里重播比赛。",
        "Don't sit down hard or skip the cooldown.": "不要硬坐或跳过冷却时间。",
        "Don't skip cooldown or sit stiff right away.": "不要跳过冷却时间或立即僵硬地坐着。",
        "Don't skip cooldown to rush the next thing.": "不要跳过冷却时间去匆忙做下一件事。",
        "Don't skip the recovery interval to chase the score.": "不要跳过恢复间隔来追逐分数。",
        "Don't skip warmup or rush the opening minutes.": "不要跳过热身或匆忙开场。",
        "Don't speed up if the legs feel heavy.": "如果腿感觉很重，不要加快速度。",
        "Don't speed up or add hills for extra credit.": "不要为了额外的学分而加快速度或增加山丘。",
        "Don't speed up or chase pace on tired legs.": "不要在疲惫的腿上加速或追逐步伐。",
        "Don't spend energy before the first point matters.": "不要在第一点重要之前花费精力。",
        "Don't sprint for every ball in the first set.": "第一盘不要每个球都冲刺。",
        "Don't stack another hard block on tired legs.": "不要在疲惫的腿上堆放另一个硬块。",
        "Don't stack demands before the body wakes up.": "在身体醒来之前不要堆叠需求。",
        "Don't stack more hard work or skip food after the effort.": "不要堆叠更多的努力工作或跳过食物后的努力。",
        "Don't start hard or skip food and water early.": "不要过早开始或不吃食物和水。",
        "Don't stay in longer to prove toughness.": "不要停留更长的时间来证明韧性。",
        "Don't stay until dizzy — leave at the first warning sign.": "不要呆到头晕-在第一个警告标志离开。",
        "Don't test fitness on a recovery walk.": "不要在康复散步时测试一下健身。",
        "Don't treat missing sleep as proof you're either ready or not ready.": "不要把错过的睡眠视为你准备好了或没有准备好的证据。",
        "Don't turn it into a forced march or a distance chase.": "不要把它变成强迫行军或远距离追逐。",
        "Don't turn it into a power walk or errands sprint.": "不要把它变成权力行走或跑腿冲刺。",
        "Don't turn the evening into extra training.": "不要把晚上变成额外的训练。",
        "Done": "完成",
        "Drink a glass of water in the next hour — fluids are low.": "在接下来的一个小时内喝一杯水-液体不足。",
        "Drink a glass of water in the next hour.": "在接下来的一个小时里喝一杯水。",
        "Drink more water and get a real meal soon.": "多喝水，很快就能吃上一顿真正的饭。",
        "Drink now, take a small bite, then settle back into an easy rhythm.": "现在喝，采取一个小的咬，然后安定下来，回到一个简单的节奏。",
        "Drink steadily now so energy and readiness stay stable.": "现在喝稳定，所以能量和准备保持稳定。",
        "Drink water and take ten easy minutes.": "喝水，放松十分钟。",
        "Drink, eat, then put the legs up for a bit.": "喝，吃，然后把腿抬起来。",
        "Drinks are behind for this point of the day.": "饮料在这一天的这一点上落后了。",
        "During a strength session, the best signal is stable movement and controlled effort. That gives you training value without adding unnecessary stress.": "在强度会话期间，最好的信号是稳定的运动和受控的努力。这给了你训练的价值，而不会增加不必要的压力。",
        "EVENING": "晚上",
        "Ease back a little.": "放松一点。",
        "Ease back until breathing is conversational again.": "放松，直到呼吸再次对话。",
        "Ease in from the first minute — no forcing.": "从第一分钟开始放松-没有强迫。",
        "Ease into each hold — nothing to force.": "放松到每一个持有-没有什么可强迫的。",
        "Ease into each hold.": "轻松进入每个保留区。",
        "Ease into sleep — rest is the final rep.": "放松进入睡眠-休息是最后的代表。",
        "Ease into the first rounds — quality intervals beat an early blow-up.": "轻松进入第一轮-质量间隔击败了早期的爆发。",
        "Ease into the night — tomorrow's legs start with sleep.": "放松到深夜-明天的腿从睡眠开始。",
        "Ease off a bit": "放松一点",
        "Ease off now — finishing easy beats pushing through.": "放松一下-完成轻松的节拍。",
        "Ease out of the hold until breathing feels easy again.": "放松，直到呼吸再次感到轻松。",
        "Easy Run": "轻松跑",
        "Easy hike day — movement without a scoreboard.": "轻松徒步旅行日-没有记分牌的运动。",
        "Easy morning": "轻松的早晨",
        "Easy movement and food — muscles rebuild on rest.": "轻松运动和食物-肌肉在休息时重建。",
        "Easy steps only — blood flow, not more load.": "只有简单的步骤-血液流动，而不是更多的负荷。",
        "Easy walk day — movement without a scoreboard.": "轻松步行一天-没有记分牌的运动。",
        "Easy walk — a soft start after short sleep.": "轻松步行-短暂睡眠后的软启动。",
        "Easy walk — gentle movement only if the body wants to wake up.": "轻松行走-只有在身体想要醒来时才进行轻柔的运动。",
        "Easy warm-up first — shorten if legs stay heavy.": "先轻松热身-如果双腿保持沉重，请缩短。",
        "Eat a light breakfast now if you haven't — \\(title) at \\(time).": "如果你还没吃早餐，现在就吃一份清淡的早餐——\\(title)at\\(time)。",
        "Eat a proper meal before the day winds down.": "在一天结束之前吃一顿适当的饭。",
        "Eat a solid meal with protein in the next couple of hours.": "在接下来的几个小时内吃一顿含蛋白质的固体餐。",
        "Eat before energy dips, not after.": "在能量消耗之前吃，而不是之后。",
        "Eat normally": "正常吃",
        "Eat normally at next meal": "下一顿饭正常吃",
        "Eat normally at the next meal": "在下一顿饭正常吃",
        "Eat normally, drink steadily, and keep the rest of the day easy.": "正常饮食，稳定饮酒，并保持一天的其余时间轻松。",
        "Eat something balanced, then start settling in.": "吃点平衡的东西，然后开始适应。",
        "Eat well, hydrate, and finish the day early.": "吃得好，补充水分，早点结束一天。",
        "Eat, shower, then start your wind-down.": "吃饭，洗澡，然后开始放松。",
        "Endurance work is banked — recovery is the job now.": "耐力工作是有银行的-恢复是现在的工作。",
        "Enough for today — keep the evening quiet.": "今天够了-保持晚上安静。",
        "Enough for today — wind down calmly.": "今天够了-冷静下来。",
        "Evening hike — help the day settle before sleep.": "晚上徒步旅行-帮助睡眠前解决一天。",
        "Evening recovery": "晚上恢复",
        "Evening walk — a gentle way to let the day settle.": "晚上散步-一种让一天安定下来的温和方式。",
        "Evening walk — help the day settle before sleep.": "晚上散步-帮助睡眠前解决一天。",
        "Extend cooldown — fifteen easy minutes before you stop.": "延长冷却时间 -- 在你停下来前15分钟。",
        "Extra five minutes warm-up before the first point.": "在第一点之前额外的五分钟热身。",
        "Extra intensity now could take away from tomorrow's performance.": "现在额外的强度可能会影响明天的表现。",
        "Extra intensity tonight is more likely to weigh on tomorrow than help today.": "今晚的额外强度更有可能给明天带来压力，而不是今天的帮助。",
        "Fifteen quiet minutes, then head toward bed.": "安静15分钟，然后走向床。",
        "Fifteen quiet minutes, then move on.": "安静15分钟，然后继续前进。",
        "Fill a bottle, pocket a snack, check shoes — then ease into the first section.": "装满瓶子，放入零食，检查鞋子-然后轻松进入第一部分。",
        "Find a quiet spot and start with five easy breaths.": "找一个安静的地方，从五个简单的呼吸开始。",
        "Fine": "好",
        "Finish this interval, then take the full rest.": "完成此间隔，然后完全休息。",
        "Finish with reserve": "完成保留",
        "First block easy — settle in before you push.": "第一块容易-在你推之前先安顿下来。",
        "First hour easy — let breathing and rhythm settle before pushing.": "第一个小时容易-在推动之前让呼吸和节奏稳定下来。",
        "First meal is still ahead.": "第一顿饭还在前面。",
        "First sets light — \\(title) at \\(time), form before load.": "首先点亮光源——\\(title)在\\(time)处形成，发生于加载前。",
        "First sets light — form over weight.": "首先设置重量轻的形式。",
        "Five minutes easy warm-up, then check the plan.": "五分钟轻松热身，然后检查计划。",
        "Five minutes easy warm-up, then start the first interval controlled.": "五分钟轻松预热，然后开始第一个间隔控制。",
        "Five quiet minutes before you move on.": "在你继续之前安静五分钟。",
        "Fluids are lower than this point of the day usually needs.": "液体低于这一点的一天通常需要。",
        "Fluids are lower than this point of the day usually needs. Rehydrating helps protect energy and readiness.": "通常情况下，一天中的这个时段，体液需求较低。补水有助于保护能量和准备状态。",
        "Focus on recovery instead of trying to fit in one more workout.": "专注于恢复，而不是试图适应一个更多的锻炼。",
        "Follow one slow exhale a little longer than the inhale.": "跟随一个缓慢的呼气比吸气长一点。",
        "Food is behind the demand of the day.": "食物落后于当天的需求。",
        "For a few days": "几天",
        "Form beats rushed reps.": "表格击败了匆忙的代表。",
        "Fuel intake is lagging the day so far.": "到目前为止，燃油摄入量滞后了一天。",
        "Fuel is behind for the current demand. Eating normally now supports steady energy without changing the whole plan.": "燃料落后于当前的需求。正常饮食现在可以在不改变整个计划的情况下支持稳定的能量。",
        "Fuel is critically low — don't start hard work until you've eaten.": "燃料严重不足-在吃完之前不要开始艰苦的工作。",
        "Fuel is lagging today's load, so this is not the moment to add intensity.": "燃料滞后于今天的负荷，所以现在不是增加强度的时候。",
        "Fuel the outing": "为郊游加油",
        "Full day — the walks already helped things settle.": "整天-散步已经帮助事情解决了。",
        "GET READY": "准备好了",
        "Glad you’re feeling energized — sleep looks closer to your usual. Want to review today’s planned session?": "很高兴你感到精力充沛 -- 睡眠看起来更接近你的平常。想回顾一下今天的会议计划吗？",
        "Go slower than usual and shorten it if heaviness stays.": "比平时慢一点，如果持续沉重，就缩短它。",
        "Good": "很好",
        "Good morning": "早上好",
        "Good to hear.": "很高兴听到。",
        "Good to hear. What would help next?": "很高兴听到。接下来会有什么帮助？",
        "Got it — energy feels normal so far.": "明白了-到目前为止，能量感觉正常。",
        "Got it — feeling tired.": "明白了——感觉有点累。",
        "Got it — not great today.": "明白了——今天状态不太好。",
        "Got it — open today’s Plan review to confirm any change. Coach won’t alter your Plan by itself.": "明白了-打开今天的计划审核以确认任何更改。教练不会改变你的计划。",
        "Got it — thanks for saying that.": "明白了-谢谢你这么说。",
        "Got it.": "好的。",
        "Got it. Want a simple meal idea anyway?": "明白了。无论如何，想要一个简单的用餐想法？",
        "HIIT done": "HIIT完成",
        "HIIT is ahead — warm up before the first hard interval.": "HIIT提前-在第一个硬间隔之前进行热身。",
        "HIIT is done — heart rate is still catching up.": "HIIT完成-心率仍在追赶。",
        "HIIT is live — hard reps, honest recovery between.": "HIIT是生活-艰难的代表，诚实的恢复之间。",
        "HRV on \\(hrvCoverage.observedDays) days — not enough for a trend": "HRV 在\\(hrvCoverage.observedDays)天内——不足以构成趋势",
        "HYDRATION": "补水",
        "Hard": "困难",
        "Hard endurance is coming — recovery is not fully there yet.": "艰苦的耐力即将到来-恢复还没有完全恢复。",
        "Hard session is on the plan tomorrow.": "明天的计划是艰苦的会议。",
        "Hard session is on the plan.": "艰难的会议正在计划中。",
        "Hard sessions on your lower-recovery days tend to make the following morning harder. Today's recovery is still low — keep that pattern in mind.": "在恢复能力较低的日子里，艰苦的训练往往会使第二天早上变得更加困难。今天的复苏仍然很低-请记住这种模式。",
        "Haven’t started": "还没开始",
        "Head out for \\(title) at \\(time) — easy pace, no target.": "前往\\(time)参加\\(title)—— 节奏轻松，不设目标。",
        "Head to bed — the day is done.": "上床睡觉-一天结束了。",
        "Health access is needed for Ask Coach.": "Ask Coach需要健康访问。",
        "Heart rate is spiked — rest until you can own the next set.": "心率飙升-休息，直到你可以拥有下一组。",
        "Heat plus high heart rate — shorten this round.": "热量加上高心率-缩短这一轮。",
        "Heat session done — cool down slowly, not in a rush.": "加热会话完成-缓慢冷却，不要着急。",
        "Heavy day stacked with hard work tomorrow.": "沉重的一天叠加着明天的辛勤工作。",
        "Heavy day — keep this walk easy.": "沉重的一天-保持轻松的步行。",
        "Heavy load is banked — hold reserve for tomorrow.": "重负荷是明天的储备。",
        "Heavy load is banked — hold the line tonight.": "沉重的负担是银行-今晚保持线。",
        "Heavy load is banked — keep tonight easy.": "沉重的负担是有银行的-今晚保持轻松。",
        "Heavy strength day — evening is for landing, not loading.": "高强度的白天-晚上是为了着陆，而不是装载。",
        "Help me choose food": "帮我选择食物",
        "Here are measurable changes since your focus window. WeekFit can’t confirm whether you followed the habit itself.": "这里有可测量的变化，因为你的焦点窗口。WeekFit无法确认您是否遵循了习惯本身。",
        "Here’s a clear read on your recent activity.": "这是您最近活动的清晰阅读。",
        "Here’s what lines up with feeling \\(feeling.bilingualTitle.english.lowercased()) — without treating this as a diagnosis.": "以下是与“\\(feeling.bilingualTitle.english.lowercased()”感受相符之处——但请勿将此视为诊断结果。",
        "Here’s what recovery looks like lately.": "这是最近的恢复情况。",
        "Here’s what’s logged for food today.": "这是今天记录的食物。",
        "Hey \\(name). How are you feeling now?": "嘿 \\ (名字)。你现在感觉怎么样？",
        "Hey \\(name). How are you feeling?": "嘿，\\(name)。你感觉怎么样？",
        "High cumulative load today.": "今天的高累积负载。",
        "Hike day — give it the respect of a real outing.": "远足日-给它一个真正的郊游的尊重。",
        "Hike is underway — stay ahead of fatigue.": "远足正在进行中-保持领先于乏力。",
        "Hit easy for five minutes, then pick your pace.": "轻松打五分钟，然后选择你的速度。",
        "Hold conversational effort — keep it honest, not heroic.": "保持对话的努力-保持诚实，而不是英勇。",
        "Hold effort flat — speed up only when breathing stays easy.": "保持平稳-仅在呼吸轻松时才加速。",
        "Hold effort flat.": "保持努力。",
        "Hold this effort.": "保持这一努力。",
        "Hold this — if sentences get short, back off one notch.": "拿着这个 -- 如果句子变得简短，退一步。",
        "Hold where it feels gentle — then ease a little deeper on the exhale.": "保持在感觉温和的地方-然后在呼气时放松一点。",
        "How am I recovering?": "我如何恢复？",
        "How are you feeling now?": "你现在感觉怎么样？",
        "How are you feeling this time?": "这次感觉怎么样？",
        "How are you feeling?": "你感觉怎么样？",
        "How consistent am I?": "我有多一致？",
        "How demanding did that \\(phrase.en) feel?": "那个 \\ (短语.en) 感觉有多苛刻？",
        "How does that compare?": "如何比较？",
        "How does your energy feel during activity today?": "在今天的活动中，你的能量感觉如何？",
        "How was my week?": "我的一周过得怎么样？",
        "How were my activities spread?": "我的活动是如何传播的？",
        "How’s your energy right now?": "你现在精力怎么样？",
        "Hydrate before the heat.": "加热前水合。",
        "I can help with how you feel, your activity, nutrition, or recovery. How are you feeling today — or what would you like to look at?": "我可以帮助你的感觉，你的活动，营养，或恢复。你今天感觉如何-或者你想看什么？",
        "I can look at your activity, nutrition, or recovery next — or tell me more about how you feel.": "接下来，我可以看看你的活动、营养或恢复情况，或者告诉我更多你的感受。",
        "If energy feels solid, keep today’s plan steady rather than adding extra load on a good feeling alone.": "如果精力充沛，请保持今天的计划稳定，而不是仅在良好的感觉上增加额外的负担。",
        "If it’s been a few days, one night isn’t the whole story. Keep the next sessions lighter until sleep looks steadier.": "如果已经过了几天，一个晚上并不是全部。保持下一个会话更轻，直到睡眠看起来更稳定。",
        "If you can, protect a slightly earlier wind-down tonight. This is optional — your Plan isn’t changed.": "如果可以的话，今晚保护稍早一点的风。这是可选的-您的计划不会更改。",
        "If you train, try completing sessions on three separate days you can log.": "如果您进行培训，请尝试在可以记录的三天内完成课程。",
        "In HIIT": "在HIIT",
        "In sauna": "在桑拿浴",
        "In session": "在会话中",
        "In the heat": "在热",
        "In the last 7 days you finished \\(completed) of \\(max(planned, completed)) planned sessions.": "在过去7天内，您完成了 \\ (最大 (计划，完成)) 计划的会话中的 \\ (完成)。",
        "In the last 7 days you finished \\(completedCount) of \\(max(plannedCount, completedCount)) planned sessions.": "在过去7天内，您完成了 \\(max (plennedcount，completedCount)) 计划会话的 \\(completedCount)。",
        "In the match": "在比赛中",
        "In the swim": "在游泳",
        "Includes \\(recoveryShare) recovery sessions among logged activities.": "在记录的活动中包括 \\(recoveryShare) 恢复会话。",
        "Is this mostly about last night’s sleep, or has it been building for a few days?": "主要是昨晚睡眠，还是这几天一直这样？",
        "Is today’s food log up to date?": "今天的食物记录是最新的吗？",
        "It started today": "今天开始",
        "It's late — the day is closed.": "很晚了-一天结束了。",
        "It's morning — and the body is still catching up.": "现在是早晨-身体仍在追赶。",
        "It's morning — sleep and recovery haven't fully landed yet.": "现在是早晨-睡眠和恢复尚未完全着陆。",
        "It’s lasted a few days": "它持续了几天",
        "I’ll help you stay on track with the adjustments you chose.": "我将帮助您保持在您选择的调整的轨道上。",
        "Just today": "就在今天",
        "Keep a sustainable pace and stay ahead on water.": "保持可持续的步伐，在水上保持领先。",
        "Keep an easy pace": "保持轻松的步伐",
        "Keep an easy, conversational pace.": "保持轻松的对话节奏。",
        "Keep at least one easier day and watch sleep coverage before adding load.": "保持至少一个轻松的一天，并在增加负荷之前手表睡眠覆盖率。",
        "Keep effort low — this is repair, not training.": "保持低努力-这是修复，而不是训练。",
        "Keep it calm — no extra court time tonight.": "保持冷静-今晚没有额外的法庭时间。",
        "Keep it calm: sleep matters more than steps right now.": "保持冷静: 睡眠比现在的步骤更重要。",
        "Keep it conversational: the goal is to wake up, not add load.": "保持对话: 目标是唤醒，而不是增加负载。",
        "Keep it easy": "保持轻松",
        "Keep it light": "保持轻松",
        "Keep it pleasant — fresh air beats forced pace.": "保持愉快-新鲜空气胜过强迫的步伐。",
        "Keep it pleasant — fresh air beats forced steps.": "保持愉快-新鲜空气胜过强制步骤。",
        "Keep it slow enough to speak in full sentences.": "保持足够慢，以便说出完整的句子。",
        "Keep logging sleep and completed sessions — a focus needs clearer patterns.": "保持记录睡眠和完成的会话-焦点需要更清晰的模式。",
        "Keep meals steady and leave hard blocks for tomorrow's session.": "保持膳食稳定，为明天的会议留出硬块。",
        "Keep meals steady and leave hard blocks for tomorrow.": "保持膳食稳定，为明天留下坚硬的积木。",
        "Keep movement light and let recovery lead the day.": "保持运动轻放，让恢复引领一天。",
        "Keep moving easy — let heart rate settle before you sit.": "保持移动容易-让心率在你坐下之前稳定下来。",
        "Keep my Plan": "保持我的计划",
        "Keep optional intensity off the table for the rest of today.": "在今天剩下的时间里，不要选择强度。",
        "Keep optional intensity off the table today.": "今天不要选择强度。",
        "Keep planned effort": "保持计划的努力",
        "Keep recovery easy": "保持轻松恢复",
        "Keep reps clean — drop weight before form slips.": "保持reps清洁-在成型单之前放下重量。",
        "Keep spare energy for when it matters tonight.": "今晚重要的时候保持多余的能量。",
        "Keep spare energy for when it matters.": "把多余的能量留到重要的时候。",
        "Keep the breath soft and unforced.": "保持呼吸轻柔和不用力。",
        "Keep the breath soft — this is calm, not a drill.": "保持呼吸柔和-这是平静，不是演习。",
        "Keep the breath soft.": "保持呼吸柔和。",
        "Keep the day flexible": "保持一天的灵活性",
        "Keep the effort comfortable and finish with control.": "保持努力舒适，并在控制下完成。",
        "Keep the evening calm so sleep can do its job.": "保持晚上的平静，这样睡眠就可以完成它的工作。",
        "Keep the evening easy.": "晚上保持轻松。",
        "Keep the evening quiet — no extra load.": "晚上保持安静-没有额外的负担。",
        "Keep the first block gentle — no intensity before you feel ready.": "保持第一块温柔-没有强度之前，你觉得准备好了。",
        "Keep the first block light — recovery is still building.": "保持第一个街区的光线-恢复仍在建设中。",
        "Keep the first hour easy; shorten the session if legs stay heavy.": "保持第一个小时的轻松; 如果腿很重，则缩短疗程。",
        "Keep the first minutes easy — recovery is still building.": "保持第一分钟轻松-恢复仍在建立。",
        "Keep the guidance in mind and I’ll help you stay on track.": "记住指导，我会帮助你保持正轨。",
        "Keep the morning easy until that session is closer.": "保持早晨轻松，直到会议接近为止。",
        "Keep the next hour unhurried — legs need quiet.": "接下来的一个小时不要着急 -- 腿需要安静。",
        "Keep the next hour unhurried.": "接下来的一个小时不要着急。",
        "Keep the next step simple and arrive ready.": "保持下一步简单，准备就绪。",
        "Keep the pace conversational. Sip and snack before you feel empty.": "保持对话的节奏。在你感到空虚之前，先喝一口小吃。",
        "Keep the rest of the day calm — no new hard block.": "保持一天剩下的时间平静-没有新的困难。",
        "Keep the rest of the day calm — nothing left to prove.": "剩下的时间保持冷静-没有什么可以证明的。",
        "Keep the rest of the day light so tomorrow's session still has quality.": "让剩下的时间保持清淡，这样明天的会议仍然有质量。",
        "Keep the rest of the day unhurried — sleep matters more than extra steps.": "保持一天的其余时间不慌不忙-睡眠比额外的步骤更重要。",
        "Keep the rest of the day unhurried.": "剩下的时间不要匆忙。",
        "Keep the rest of today easy so tomorrow's training stays useful.": "保持今天剩下的时间轻松，这样明天的培训就会有用。",
        "Keep the rest of today easy — nothing to prove tonight.": "今天剩下的时间保持轻松-今晚没有什么可以证明的。",
        "Keep the rest of today easy, then protect sleep.": "保持今天的休息轻松，然后保护睡眠。",
        "Keep the rest of today light on the legs.": "今天剩下的时间保持在腿上。",
        "Keep this hike easy — today it counts as recovery.": "保持这次加息轻松-今天算作恢复。",
        "Keep this one easy.": "把这个保持简单。",
        "Keep this run easy": "保持这个运行容易",
        "Keep this walk easy — today it counts as recovery.": "保持轻松的步行-今天它被视为恢复。",
        "Keep today calm — hold an easy rhythm from here.": "保持今天的平静-从这里保持轻松的节奏。",
        "Keep today calm — tomorrow needs fresh legs.": "保持今天的平静-明天需要新鲜的腿。",
        "Keep today easy — no extra hard blocks.": "保持今天轻松-没有额外的硬块。",
        "Keep today easy — tomorrow needs capacity.": "保持今天轻松-明天需要容量。",
        "Keep today easy, then protect sleep tonight.": "保持今天轻松，然后保护今晚的睡眠。",
        "Keep today light so tomorrow's session still has quality.": "保持今天的光明，所以明天的会议仍然有质量。",
        "Keep today lighter if you can, and notice how you feel after rest — without forcing a training change.": "如果可以的话，保持今天的轻松，并注意休息后的感觉-不要强迫训练改变。",
        "Keeping your Plan as is. You can always revisit Coach later.": "保持你的计划。你可以随时回访教练。",
        "Last 7 days": "近 7 天",
        "Last 7 nights": "近 7 晚",
        "Last night": "昨晚",
        "Last set done": "最后一组完成",
        "Last set done — muscles are still loaded and warm.": "最后一组完成-肌肉仍然负荷和温暖。",
        "Last time we looked at protein. Want a meal idea for today?": "上次我们看了蛋白质。今天想吃饭吗？",
        "Later today: \\(title) at \\(activity.formattedStartTime).": "今天晚些时候: \\ (标题) 在 \\(activity.formattedStartTime)。",
        "Lay out water, snacks, and layers — then leave at a sustainable pace.": "布置水，小吃和层-然后以可持续的速度离开。",
        "Leave hard blocks off the calendar until tomorrow.": "把日历上的硬块留到明天。",
        "Leave turnaround margin — the way back still counts.": "留出周转余地-回来的路仍然很重要。",
        "Leg day is next — ease in before you load heavy.": "腿日是下一个-在你负重之前放松一下。",
        "Leg day is next — legs aren't fully topped up.": "腿日是下一个-腿还没有完全充满。",
        "Leg day is next — prime hips and knees first.": "腿日是下一个-首先是臀部和膝盖。",
        "Legs are under load — reps and sets are live.": "腿在负荷下-代表和集合是活的。",
        "Let heart rate and pace drift down; nothing to prove.": "让心率和速度漂移下来; 没有什么可以证明的。",
        "Let muscles cool — then protein and water.": "让肌肉冷却-然后是蛋白质和水。",
        "Let the walk release tension, not add another block.": "让步行释放张力，而不是增加另一个块。",
        "Let’s start with how you feel.": "让我们从你的感受开始。",
        "Lifting now": "现在提升",
        "Light first sets — \\(titleEN) at \\(time).": "先点亮灯光 —\\(titleEN)在\\(time)处。",
        "Light food and fluids — nothing heavy on the stomach.": "轻的食物和液体-没有重的胃。",
        "Light movement and hydration — keep the softness.": "轻运动和水合-保持柔软。",
        "Listed nights had recorded sleep below the average for this period.": "列出的夜晚记录的睡眠低于此期间的平均水平。",
        "Load has already accumulated today, so recovery affects the effort ceiling but does not replace the current workout.": "负载今天已经累积，因此恢复会影响努力上限，但不会取代当前的锻炼。",
        "Load is already high — ease this session.": "负载已经很高-轻松进行此会话。",
        "Logged on \\(activeDays) of \\(bundle.currentDays.count) days": "已登录 \\ (活动天数) \\(bundle.currentDays.count) 天",
        "Logged on \\(sessionCoverage.observedDays) of \\(sessionCoverage.totalDays) days": "已登录 \\(sessionCoverage.observedDays) 的 \\(sessionCoverage.totalDays) 天",
        "Long Run": "长跑",
        "Long hike done — the body still needs a soft landing.": "长途徒步旅行完成-身体仍然需要软着陆。",
        "Long session — plan fuel and fluids ahead of time.": "长时间会议-提前计划燃料和液体。",
        "Long walk day — time on feet adds up.": "长时间步行-步行时间加起来。",
        "Longer warm-up — first games at half speed.": "更长的热身-半速的第一场比赛。",
        "Look at my eating habits": "看看我的饮食习惯",
        "Look at the last 7 days": "看看过去的7天",
        "Looking at \\(loggedDays.count) logged days in the last week (not every day). Average protein on those days was about \\(avgProtein) g.": "查看 \\(loggedDays.count) 上周 (不是每天) 记录的天数。这些天的平均蛋白质约为 \\(avgProtein) g。",
        "Low energy": "低能量",
        "Lower than usual": "比平时低",
        "Main work is done — keep today easy from here.": "主要工作已经完成-从这里保持今天轻松。",
        "Main work is done — the day can land calmly now.": "主要工作已经完成-现在可以平静地降落了。",
        "Main work is done — the evening can stay calm.": "主要工作完成-晚上可以保持冷静。",
        "Make recovery easier to start": "使恢复更容易开始",
        "Make the evening quieter": "让夜晚更安静",
        "Match day is coming — protect energy until it's time.": "比赛日即将到来-保护能源，直到它的时间。",
        "Match demand is real — you are not fully topped up.": "匹配需求是真实的-您没有完全加满。",
        "Match done": "匹配完成",
        "Match is close — legs and focus aren't fully topped up.": "比赛是近距离的-腿部和注意力没有完全集中。",
        "Match is close — recovery isn't fully back yet.": "比赛即将结束-恢复尚未完全恢复。",
        "Match is close — sharp mind beats rushed legs.": "比赛很接近-敏锐的头脑击败了匆忙的腿。",
        "Match is over — recovery comes first.": "比赛是过度的-恢复是第一位的。",
        "Match over — legs and nerves are still lit up.": "比赛结束-腿和神经仍然发亮。",
        "Match soon": "比赛很快",
        "Max effort is fine in a burst — don't live there between intervals.": "最大的努力是好的，在爆发之间不要住在那里。",
        "Meal idea": "用餐理念",
        "Missing days aren’t treated as zeros — only recorded nights and scores count.": "错过的日子不会被视为零-仅记录的夜晚和分数计数。",
        "Mobility first — skip a heavy opener if needed.": "机动性第一-如果需要，跳过沉重的开瓶器。",
        "Moderate": "中等",
        "More consistent sleep timing": "更一致的睡眠时间",
        "Morning adjustments are already on the plan.": "早上的调整已经在计划中了。",
        "Morning plan": "早晨计划",
        "Morning work is done — keep the afternoon easy.": "上午的工作已经完成-下午保持轻松。",
        "Morning — recovery data is still catching up.": "早上恢复数据仍在追赶。",
        "Morning — short night at \\(sleepEN), recovery at \\(recovery)%.": "上午——\\(sleepEN)时段短暂休整，\\(recovery)时段恢复至 %。",
        "Morning — sleep \\(sleepEN), recovery at \\(recovery)% — not fully topped up.": "早晨 — 睡眠\\(sleepEN)，恢复率为\\(recovery)% — 尚未完全恢复。",
        "Morning — sleep \\(sleepEN), recovery at \\(recovery)%.": "早晨 — 睡眠\\(sleepEN)，恢复率为\\(recovery)%。",
        "Morning — yesterday logged real training load — keep today's first block softer.": "早上-昨天记录了真实的训练负荷-保持今天的第一个方块更柔和。",
        "Morning — yesterday logged real training load, sleep \\(sleep), recovery \\(facts.recoveryPercent)%.": "早上——昨天有实际训练负荷，睡眠 \\(sleep)，恢复 \\(facts.recoveryPercent)%。",
        "Morning — yesterday logged real training load, sleep \\(sleepEN), recovery at \\(recovery)%.": "晨间记录：昨日实际训练负荷为 X，睡眠时长为\\(sleepEN)，恢复率为\\(recovery)%。",
        "Most recent sleep looks too old to treat as current.": "最近的睡眠看起来太老了，不能当作电流。",
        "My Assessment": "我的评估",
        "My Recommendation": "我的建议",
        "NUTRITION": "营养",
        "Need at least \\(Minimums.sleepAverage) recorded nights.": "至少需要 \\ (最低睡眠水平) 记录的夜晚。",
        "Next meal": "下一餐",
        "Next up: \\(title) at \\(activity.formattedStartTime).": "下一步: \\ (标题) 在 \\(activity.formattedStartTime)。",
        "Nice work": "干得好",
        "Nights shorter than your period average (\\(AskCoachCopy.sleepHours(from: avg).english)).": "比您的平均时间短的夜晚 (\\(AskCoachCopy.sleepHours (来自: avg)。英语))。",
        "No": "否",
        "No completed activities were logged in this period.": "在此期间未记录任何已完成的活动。",
        "No drinks logged today. Take a few sips when it's safe to stop.": "今天没有饮料记录。可以安全停车时喝几口。",
        "No drinks logged today. Take a few sips when you can.": "今天没有记录任何饮品。可以的时候喝几一口。",
        "No drinks logged yet today. Small sips if thirsty, then wind down.": "今天还没有饮料记录。如果渴了，小口，然后放松。",
        "No early surges you'll regret later.": "没有早期的激增，你以后会后悔的。",
        "No extra hard blocks tonight.": "今晚没有额外的硬块。",
        "No grinding reps on tired stabilizers.": "没有磨损稳定器的研磨代表。",
        "No hero dives on tired legs.": "没有英雄会在疲惫的双腿上潜水。",
        "No hero intervals on tired legs.": "疲惫的双腿没有英雄间隔。",
        "No late drills or heavy legs before bed.": "睡觉前不要晚钻或重腿。",
        "No late hard efforts or long screen time in bed.": "没有迟到的努力或长时间的屏幕时间在床上。",
        "No late intensity or extra recovery tasks.": "没有后期强度或额外的恢复任务。",
        "No late screens or hard conversations in bed.": "没有迟到的屏幕或在床上进行艰苦的交谈。",
        "No late sets or heavy stairs before bed.": "睡前没有晚点或沉重的楼梯。",
        "No need to change the plan": "不需要改变计划",
        "No need to rethink the morning adjustments — focus on executing what you chose.": "无需重新考虑早晨的调整-专注于执行您选择的内容。",
        "No new hard block today — recovery comes first.": "今天没有新的硬块-恢复是第一位的。",
        "No scoreboard today — easy pace is enough.": "今天没有记分牌-轻松的步伐就足够了。",
        "No screens, no plans, no last-minute load.": "没有屏幕，没有计划，没有最后一分钟的负载。",
        "Normal": "正常",
        "Not enough data from \\(noun.english) to compare.": "\\ (名词。英语) 没有足够的数据进行比较。",
        "Not enough recent data yet": "还没有足够的最新数据",
        "Not enough recorded data for this question yet.": "没有足够的记录数据为这个问题。",
        "Not enough sleep nights to highlight shorter days.": "没有足够的睡眠夜晚来突出较短的白天。",
        "Not great": "不太好",
        "Not sure": "不确定",
        "Nothing heavy is on the calendar yet.": "日历上还没有沉重的东西。",
        "Nothing left to optimize tonight — sleep is the move.": "今晚没有什么可以优化的-睡眠是移动。",
        "Nothing logged for today yet — that just means we don’t have movement on record.": "今天还没有记录 -- 这只是意味着我们没有记录在案的动静。",
        "Nothing urgent is pulling the day off balance.": "没有什么紧急的事情可以使这一天失去平衡。",
        "Nothing urgent — though energy is softer than usual.": "没什么紧急的-尽管能量比平时更柔和。",
        "Notice where you hold tension — breathe into it.": "注意你在哪里保持紧张-呼吸它。",
        "Numbers don’t fully explain it": "数字不能完全解释它",
        "Nutrition": "营养",
        "ON TRACK": "在轨道上",
        "Okay": "还行",
        "On the ride": "在骑",
        "On the run": "在逃",
        "One easier minute, then settle back into the planned pace.": "轻松一分钟，然后回到计划的速度。",
        "One short loop, then home — no surges.": "一个短循环，然后回家-没有浪涌。",
        "Only days with at least one completed session are shown.": "仅显示具有至少一个已完成会话的天数。",
        "Only metrics with enough samples in both periods are compared.": "仅比较两个时期中具有足够样本的度量。",
        "Open Meals": "打开饮食",
        "Open Profile": "打开个人资料",
        "Open lighter than planned — first sets are a readiness check.": "打开比计划轻-第一套是准备检查。",
        "Open morning — \\(title) is tomorrow at \\(tomorrow.formattedStartTime).": "上午开放 —\\(title)将于明日在\\(tomorrow.formattedStartTime)举行。",
        "Open with a short warm-up, then hit intervals clean — not all-out from round one.": "短暂的热身打开，然后从第一轮开始打间隔干净-不是全部。",
        "Optional — skip if you’d rather go straight to the comparison.": "可选-如果您想直接进行比较，请跳过。",
        "Other topic": "其他主题",
        "Over the last 7 days there aren’t completed training or movement logs in the planner yet.": "在过去的7天里，规划器中还没有完成的培训或运动日志。",
        "Over the last 7 days there isn’t enough logged activity to summarize yet.": "在过去的7天里，没有足够的记录活动来总结。",
        "Over the last 7 days there isn’t enough logged nutrition to describe a pattern. Unlogged days aren’t treated as zero intake.": "在过去的7天里，没有足够的营养记录来描述一种模式。未记录的天数不被视为零摄入量。",
        "Over the last 7 days there isn’t much completed movement on the log yet.": "在过去的7天里，日志上还没有太多完整的移动。",
        "Over the last 7 days you’ve logged \\(label.english) — about \\(duration.english) in total.": "在过去 7 天内，您已登录\\(label.english)次——总计约\\(duration.english)次。",
        "Over the last 7 days you’ve logged \\(sessions) sessions — about \\(duration.english) in total.": "在过去 7 天内，您共登录了\\(sessions)次会话——总计约\\(duration.english)次。",
        "Pace the day": "节奏的一天",
        "Pace the outing": "步伐的郊游",
        "Pack a snack you can eat without stopping long.": "打包一份零食，你可以不用长时间停下来吃。",
        "Pack water for the whole outing — top up before you leave.": "为整个郊游打包水-在你离开之前把水顶上。",
        "Pack water, salty snacks, and a light layer before the first hard climb.": "在第一次艰难的攀登之前，要装水，咸味小吃和淡淡的一层。",
        "Pack water, snacks, and layers before you go.": "在你走之前，打包水、零食和分层。",
        "Past halfway — easy effort still counts as recovery.": "过去的一半-轻松的努力仍然算作恢复。",
        "Patience in the middle miles — consistency beats spikes.": "中间英里的耐心-一致性击败尖峰。",
        "Pick a bedtime and stick to it.": "选择一个睡觉时间并坚持下去。",
        "Pick one priority block before noon.": "在中午之前选择一个优先块。",
        "Pick today's first block.": "选择今天的第一个街区。",
        "Pick your battles — not every ball needs a sprint.": "选择你的战斗-不是每个球都需要冲刺。",
        "Plan a solid breakfast before the session.": "在会议前计划一顿丰盛的早餐。",
        "Plan vs logged": "计划与记录",
        "Planner sessions completed: \\(plannedCompleted) of \\(plannedTotal).": "计划程序会话已完成: \\(plannedCompleted) 的 \\(plannedTotal)。",
        "Play for position, not power — shorten points when you can.": "发挥的位置，而不是权力-缩短点，当你可以。",
        "Play the next points within yourself, not at full stretch.": "在自己的内心发挥下一点，而不是全力以赴。",
        "Point by point.": "逐点。",
        "Prep water and a snack — this outing deserves it.": "准备水和小吃-这次郊游值得。",
        "Prepare for sleep": "准备睡觉",
        "Prepare for training": "准备培训",
        "Preparing for HIIT": "准备HIIT",
        "Preparing to ride": "准备骑行",
        "Preparing to run": "正在准备运行",
        "Preparing to swim": "准备游泳",
        "Prioritize nights closer to your recent average sleep duration.": "优先考虑接近你最近的平均睡眠时间的夜晚。",
        "Protect recovery this week": "本周保护恢复",
        "Protect the main effort": "保护主要努力",
        "Protect tomorrow's ride": "保护明天的骑行",
        "Protect your energy": "保护你的能量",
        "Protein and fluids within the next hour.": "蛋白质和液体。",
        "Protein is \\(proLogged) g of \\(proGoal) g — about \\(nutrition.proteinRemaining) g left.": "蛋白质为\\(proLogged)g，减去\\(proGoal)g 后，剩余约\\(nutrition.proteinRemaining)g。",
        "Protein is \\(proLogged) g of \\(proGoal) g — close to your target.": "蛋白质为\\(proLogged)g 或\\(proGoal)g —— 已接近您的目标值。",
        "Protein is about \\(Int((-delta).rounded())) g over today’s \\(proGoal) g goal.": "蛋白质含量约为\\(Int((-delta)，较当前\\(proGoal)的目标值有所提升。",
        "Quality reps only — cut a set before form breaks on a stacked day.": "仅限质量代表——在连续生产日出现模具故障前完成一批产品的切割。",
        "Quick check": "快速检查",
        "Quick check-in. How’s your body feeling?": "快速确认一下。身体感觉如何？",
        "Quiet day — the body is asking for margin, not more load.": "静默之日——机体需要的是安全裕度，而非额外的负荷。",
        "Quiet room — soft breaths from the start.": "静谧的房间——从一开始，便传来轻柔的呼吸声。",
        "RECOVERY": "康复",
        "Racket day is in the books — evening is for recovery.": "击球日已定——傍晚则用于恢复。",
        "Recent sleep \\(sleepText.english) is a bit longer than your baseline (\\(baselineText.english)).": "最近的睡眠时长\\(sleepText.english)略长于您的基线值（\\(baselineText.english)）。",
        "Recent sleep \\(sleepText.english) looks typical for you (baseline \\(baselineText.english)).": "最近的睡眠\\(sleepText.english)数据与您（基线\\(baselineText.english)）的情况相符。",
        "Recent sleep \\(sleepText.english) vs baseline \\(baselineText.english).": "近期睡眠期\\(sleepText.english)与基线期\\(baselineText.english)的比较。",
        "Recent sleep \\(sleepText.english) — about \\(abs(delta))m shorter than your recent baseline (\\(baselineText.english)). Shorter sleep may be one contributor.": "近期睡眠 \\(sleepText.english)——比你最近的基线（\\(baselineText.english)）大约短 \\(abs(delta)) 分钟。睡眠偏短可能是原因之一。",
        "Recent sleep, HRV, or resting heart rate readings aren’t available yet — they may still be syncing, or weren’t recorded.": "近期睡眠、HRV 或静息心率数据还不可用——可能仍在同步，或尚未记录。",
        "Recorded sleep averaged at least 30 minutes shorter than before.": "记录到的睡眠时长较此前平均缩短至少 30 分钟。",
        "Recovering": "恢复中",
        "Recovering now": "正在恢复",
        "Recovery": "恢复",
        "Recovery Run": "恢复跑",
        "Recovery \\(recovery)% looks typical for you (baseline \\(baseline)%).": "您的恢复率\\(recovery)% 与您的基线值\\(baseline)% 基本相符。",
        "Recovery \\(recovery)% vs baseline \\(baseline)%.": "恢复率\\(recovery)% 与基线值\\(baseline)% 的对比。",
        "Recovery \\(recovery)% — about \\(abs(delta)) points below your recent baseline (\\(baseline)%). This measurement is softer than usual for you.": "恢复值\\(recovery)% — 较您最近的基线值（\\(baseline)%）低约\\(abs(delta)个百分点。此测量值对您而言较往常更为平缓。",
        "Recovery ahead": "复苏在即",
        "Recovery baseline from \\(evidence.recoverySampleCount) days": "\\(evidence.recoverySampleCount)天后的恢复基线值",
        "Recovery block is next — gentle from the first minute.": "接下来是恢复阶段——从第一分钟起即以轻柔的力度进行。",
        "Recovery comes next": "接下来是恢复阶段",
        "Recovery day": "恢复日",
        "Recovery day is closing — protect the calm tonight.": "恢复日即将结束——今晚请守护内心的平静。",
        "Recovery does not support long high-intensity rallies today.": "今日市场反弹未能支撑起长时间的高强度上涨行情。",
        "Recovery does not support productive hard running today.": "Recovery 目前不支持高效硬跑训练。",
        "Recovery hasn't caught up after recent strain.": "近期疫情暴发后，恢复进程仍未跟上。",
        "Recovery is lagging — keep the evening quiet.": "恢复进度较慢——今晚保持安静。",
        "Recovery is lagging — keep the next block lighter.": "恢复进度滞后——请保持下一个区块更轻。",
        "Recovery is lagging — protect the session.": "恢复进度滞后——请保护当前会话。",
        "Recovery is lagging — rest is the plan.": "恢复进度滞后——休息才是关键。",
        "Recovery is lagging — rest matters more now.": "恢复进度较慢——现阶段休息更为重要。",
        "Recovery is low — keep effort honest, not heroic.": "康复率较低——请保持务实的努力，而非追求英雄主义。",
        "Recovery is still catching up, so easy effort is the better call.": "恢复进度仍较慢，因此采取简单的措施才是更好的选择。",
        "Recovery is trending a little better.": "复苏态势略有改善。",
        "Recovery looks a little softer lately.": "最近恢复情况似乎稍显疲软。",
        "Recovery looks solid — tomorrow already has real work on the calendar.": "复苏态势十分稳固——明天日程中已安排了切实的工作。",
        "Recovery looks steady.": "复苏态势平稳。",
        "Recovery matters today — energy is softer than usual.": "复苏如今至关重要——能源市场较往常更为疲软。",
        "Recovery mode": "恢复模式",
        "Recovery morning": "康复晨间",
        "Recovery needs sleep more than anything else tonight.": "今晚，恢复所需的首要条件便是睡眠。",
        "Recovery score averaged \\(delta) points higher than \\(previous.english) (recorded days only).": "恢复评分平均比\\(previous.english)高出\\(delta)分（仅记录天数）。",
        "Recovery score averaged \\(drop) points lower than \\(previous.english) (recorded days only).": "恢复评分平均比\\(previous.english)低\\(drop)分（仅记录天数）。",
        "Recovery score matched \\(previous.english) where both had enough samples.": "在双方均拥有足够样本的情况下，将恢复评分与\\(previous.english)进行匹配。",
        "Recovery session is live — slow and present.": "恢复环节现已开启——节奏舒缓，专注当下。",
        "Recovery session wrapped — calm should linger.": "恢复环节已结束——平静感应持续存在。",
        "Recovery signals are still limited.": "恢复信号仍然有限。",
        "Recovery source day: \\(dayKey)": "恢复源日期：\\(dayKey)",
        "Recovery tips": "恢复建议",
        "Recovery walk — keep it easy.": "康复步行——动作要轻柔。",
        "Recovery walk — the body needs a soft reset.": "恢复性步行——身体需要一次温和的重启。",
        "Recovery walk — yesterday's or today's load still lingers.": "恢复性步行——昨日的或今日的负荷仍挥之不去。",
        "Recovery work is done — carry the calm forward.": "恢复工作已完成——将这份平静延续下去。",
        "Regular": "常规",
        "Reset between points.": "在两点之间重置。",
        "Rest and quiet — let pulse settle before what's next.": "静养与安宁——在开启下一段旅程前，让脉搏归于平静。",
        "Rest enough to keep form clean on every rep.": "充分休息，以确保每次重复动作时都能保持标准姿势。",
        "Rest or walk briefly before anything demanding.": "在进行任何高强度活动前，请先休息或短暂散步。",
        "Restore fluids": "补充体液",
        "Restore fluids, eat normally, and close the evening calmly so you can start tomorrow with reserve.": "补充水分，正常饮食，平静地结束这一天，以便您以充沛的精力迎接明天。",
        "Review Plan suggestion": "审阅计划建议",
        "Review my focus": "回顾我的关注点",
        "Review my week": "回顾本周",
        "Review plan": "查看计划",
        "Review session": "评审会议",
        "Ride done": "骑行结束",
        "Ride is ahead — legs aren't topped up, so ease in.": "骑行已进行——双腿尚未补充能量，请放慢节奏。",
        "Ride is ahead — recovery isn't fully back yet.": "复苏势头已现——但恢复工作尚未完全完成。",
        "Ride is banked — recovery is the job now.": "骑行已告一段落——现在的任务是恢复。",
        "Ride is coming — time to settle pace and legs.": "骑行季即将到来——是时候调整节奏与腿部耐力了。",
        "Ride is done — legs are still spinning inside.": "骑行结束了——双腿仍在体内打转。",
        "Roll or stretch shoulders for ten minutes.": "进行肩部环绕或拉伸运动十分钟。",
        "Run done": "运行完成",
        "Run is ahead — dial in effort before the first mile.": "赛程已过半——在跑完第一英里前，务必全力以赴。",
        "Run is ahead — legs aren't topped up, so ease in.": "跑步仍在继续——双腿尚未恢复体力，请放慢节奏。",
        "Run is ahead — recovery isn't fully back yet.": "复苏势头正在增强——但恢复尚未完全回归。",
        "Run is banked — recovery is the job now.": "奔跑已成过去——如今的重任是恢复。",
        "Run is done — heart rate is still catching up.": "跑步已结束——但心率仍在逐渐恢复。",
        "Running low on fuel for this session — eat now.": "本次会话的燃料即将耗尽——请立即补充。",
        "Sauna is next — calm entry beats heroic heat.": "接下来是桑拿——静谧的入口，胜过炽热的体验。",
        "Save energy for tomorrow": "为明天节约能源",
        "Save for tomorrow": "留待明日",
        "Save it for tomorrow": "留给明天",
        "Serious work is already on the books today.": "如今，严肃的工作已经正式列入日程。",
        "Session complete": "会话已结束",
        "Session done": "会话已结束",
        "Session is ahead — arrive calm, not already chasing.": "环节尚未开始——请保持冷静，切勿急于应对。",
        "Session is ahead — recovery isn't fully back yet.": "局面仍在演变——复苏尚未完全恢复。",
        "Session is ahead — the body isn't topped up, so ease in.": "疗程即将结束——体内能量尚未补充完毕，请放松。",
        "Session just ended — body is still buzzing.": "会议刚刚结束——体内仍阵阵发烫。",
        "Set your pace": "掌控自己的节奏",
        "Set your pace — don't chase from the gun.": "掌控自己的节奏——不要紧追枪口。",
        "Settle in a few minutes early — \\(title) at \\(time).": "提前几分钟抵达——\\(title)位于\\(time)。",
        "Settle into the ride before increasing your effort.": "在增加运动强度前，先适应骑行节奏。",
        "Settle into the run before increasing your effort.": "在增加运动强度之前，先适应跑步节奏。",
        "Settle into the session before increasing your effort.": "在加大努力之前，先充分进入状态。",
        "Settle into the swim before increasing your effort.": "先适应游泳节奏，再逐渐加大强度。",
        "Short first round — listen to your body early.": "首轮赛程较短——尽早倾听身体的信号。",
        "Short night — protect sleep tonight.": "今晚少熬夜——守护您的睡眠。",
        "Short night — recovery matters more now.": "夜晚短暂——如今恢复更为重要。",
        "Short points, quick resets — don't burn matches on a full day.": "短时操作，快速重置——避免整日频繁点燃火柴。",
        "Short rounds — cool breaks beat heroic sweats.": "短跑回合——清爽的间歇胜过艰苦的挥汗。",
        "Short rounds, cool breaks.": "短距离回合，短暂的休息。",
        "Short walk to flush the legs after hard work.": "高强度运动后，只需短距离步行即可促进腿部排水。",
        "Shorten if needed": "如有需要，请缩短",
        "Shorten points — let the opponent make mistakes.": "缩短回合——诱使对手犯错。",
        "Shorter rounds than usual — heat stacks fast on a depleted day.": "回合数较往常缩短——在体力耗尽的日子里，热量堆积速度会加快。",
        "Shorter sleep may be one contributor; we’re not claiming it caused how you feel.": "睡眠时间缩短可能是其中一个因素；但我们并非认为这直接导致了您的感受。",
        "Show what I have left": "显示我剩余的内容",
        "Shower, eat lightly, then unplug.": "淋浴后，清淡饮食，然后拔掉电源插头。",
        "Similar signals in your data": "您的数据中出现了类似信号",
        "Sip early — don't wait for thirst to catch up.": "尽早饮水——别等到口渴才行动。",
        "Sip gradually instead of catching up at once": "循序渐进，而非一蹴而就",
        "Sip if thirsty, then wind down.": "若感到口渴，则休息。",
        "Sip some water if thirsty, then rest.": "口渴时喝点水，然后休息。",
        "Sit or lie still — let nervous system downshift.": "静坐或静卧——让神经系统进入“降速”状态。",
        "Skip": "跳过",
        "Sleep and recovery can still tell a useful story when available.": "只要条件允许，睡眠与恢复情况仍可提供有价值的信息。",
        "Sleep baseline from \\(evidence.sleepSampleCount) nights": "基于\\(evidence.sleepSampleCount)晚次的睡眠基线数据",
        "Sleep baseline needs \\(CoachFeelingEvidenceRules.minimumSleepBaselineSamples)+ nights (have \\(evidence.sleepSampleCount)).": "睡眠基线需求为\\(CoachFeelingEvidenceRules.minimumSleepBaselineSamples)+ 个夜晚（具备\\(evidence.sleepSampleCount)）。",
        "Sleep coverage is thin (\\(sleepCoverage.observedDays) of \\(sleepCoverage.totalDays) nights), so keep conclusions light.": "睡眠覆盖度较低（\\(sleepCoverage.observedDays)或\\(sleepCoverage.totalDays)个夜晚），因此结论应谨慎表述。",
        "Sleep duration varied by about \\(consistencyMinutes) minutes.": "睡眠时长差异约为\\(consistencyMinutes)分钟。",
        "Sleep duration varied substantially across recorded nights.": "在记录的各夜中，睡眠时长存在显著差异。",
        "Sleep is the clearest recovery signal right now.": "睡眠是目前最明确的恢复信号。",
        "Sleep now — nothing else matters tonight.": "现在睡觉——今晚其他一切都无关紧要。",
        "Sleep now — tomorrow starts fresh.": "好好睡觉——明天将从新开始。",
        "Sleep source day: \\(dayKey)": "睡眠来源日：\\(dayKey)",
        "Sleep was not bad, but the body still needs recovery. Extra load now is likely to bring less benefit.": "睡眠状况尚可，但身体仍需要恢复期。此时增加额外负荷，可能收效甚微。",
        "Sleep was recorded on only \\(sleepCoverage.observedDays) of \\(sleepCoverage.totalDays) nights, so averages stay provisional.": "仅在\\(sleepCoverage.totalDays)个夜晚中的\\(sleepCoverage.observedDays)个夜晚记录了睡眠数据，因此平均值仍为暂定值。",
        "Sleep was short — ease into what's next.": "睡眠时间较短——请从容进入下一阶段。",
        "Sleep was short — keep today easy.": "睡眠不足——今天请保持轻松。",
        "Sleep was short — start easier than usual.": "睡眠时间较短——入睡比平时更容易。",
        "Sleep was short, so keeping this session easy is the right call.": "睡眠时间较短，因此将本次环节控制在简单程度上是正确的选择。",
        "Sleep wasn't recorded today, so I'm basing guidance on your plan and activity—not recovery metrics.": "今天未记录睡眠情况，因此我的指导将基于您的计划与活动——而非恢复指标。",
        "Sleepiness": "嗜睡",
        "Slow down until breathing is easy again.": "逐渐放慢速度，直到呼吸重新变得顺畅。",
        "Slow pace before bed.": "睡前放慢节奏。",
        "Slow pace, soft light — nothing to chase.": "节奏舒缓，光线柔和——无需追赶。",
        "Slow the breath until it feels calm again.": "缓缓呼吸，直到感觉重新平静下来。",
        "Small session logged": "已记录短会话",
        "Small steps today beat stacking load later.": "今日小步先行，胜于日后堆叠重负。",
        "Small, steady moves beat stacking load later.": "小而稳健的举措，胜过事后堆积负担。",
        "Snacks early and often — don't wait until empty.": "早吃、多吃——别等到肚子空了才吃。",
        "So far you’ve logged \\(calLogged) kcal and \\(proLogged) g protein.": "截至目前，您已记录\\(calLogged)kcal 热量及\\(proLogged)g 蛋白质。",
        "So far: \\(calLogged) of \\(calGoal) kcal, and \\(proLogged) of \\(proGoal) g protein.": "截至目前：\\(calLogged)为\\(calGoal)kcal，\\(proLogged)为\\(proGoal)g 蛋白。",
        "So far: \\(calLogged) of \\(calGoal) kcal, and \\(proLogged) of \\(proGoal) g protein. Still about \\(calLeft) kcal and \\(proLeft) g protein left today.": "截至目前：\\(calLogged)为\\(calGoal)kcal，\\(proLogged)为\\(proGoal)g 蛋白。今日仍剩余约\\(calLeft)kcal 及\\(proLeft)g 蛋白。",
        "Soft from minute one — no pressure.": "从第一刻起就柔软——毫无压力。",
        "Soften the pose until breathing feels easy again.": "逐渐放松体位，直到呼吸再次变得顺畅。",
        "Sore muscles": "肌肉酸痛",
        "Spend today calmly so tomorrow's session still has room to breathe.": "今天平静度过，让明天的交易时段仍有喘息之机。",
        "Spread training across more days": "将培训时间分散到更多天数内进行",
        "Squash is close — recovery isn't fully back yet.": "squash 已接近恢复——但恢复尚未完全完成。",
        "Squash is close — sharp feet beat rushed swings.": "壁球已近在咫尺——敏捷的脚步胜过仓促的挥拍。",
        "Squash places high demands on movement and recovery. Today's ceiling is lower than normal.": "壁球运动对身体活动与恢复提出了较高要求。如今，运动极限已较以往有所降低。",
        "Stacked day — stopping now protects tomorrow.": "叠层日——此刻止步，方能守护明日。",
        "Start a new conversation": "开启新对话",
        "Start calmly, keep form clean, and finish with reserve.": "冷静开局，保持技术动作干净利落，最后以稳健收束收尾。",
        "Start easier than planned and reassess after warming up.": "起步比原计划更轻松，并在热身后重新评估。",
        "Start easier than the first climb invites.": "起步难度低于首次攀登挑战。",
        "Start easy — find a steady stroke before any speed work.": "从简单开始——在进行速度训练之前，先找到稳定的划水节奏。",
        "Start easy — let breathing and rhythm find their place.": "从简单处开始——让呼吸与节奏自然进入状态。",
        "Start easy — let cadence and breathing find their place.": "轻松开始——先让踏频与呼吸到位。",
        "Start easy — warm up before the hard work.": "从简单开始——在正式投入之前先进行热身。",
        "Start easy, check feet early, and leave something in the tank.": "起步要轻松，尽早检查脚部状况，并在水箱中留些水。",
        "Start even more conservatively — fatigue means packing and pacing matter more.": "采取更为保守的策略——在疲劳状态下，携带装备与节奏把控尤为重要。",
        "Start lighter than planned and leave room to finish strong.": "比计划更轻松地开始，留出余力强势收尾。",
        "Start lighter than the plan says.": "启动时的负载应低于计划值。",
        "Start lighter, shorten if needed, and leave room to feel better at the end.": "从轻度开始，必要时缩短时长，并在结束时留出时间以恢复舒适感。",
        "Start slower than the calendar suggests — feel first.": "起步速度要比日历上显示的慢一些——先感受感觉。",
        "Start steadier than yesterday's peak effort.": "比昨日的全力冲刺更稳健地开始。",
        "Start steady — leave room to feel better by midday.": "循序渐进地开始——为中午时分感觉好转留出空间。",
        "Start with an easy neck or hip opener — no forcing.": "从简单的颈部或髋部拉伸动作开始——切勿强行拉伸。",
        "Stay below \\(cap) and walk at a comfortable pace.": "保持在\\(cap)以下，用舒适的步速走。",
        "Stay conversational": "保持对话氛围",
        "Stay easy until the planned time is done.": "在预定时间结束前，保持轻松状态。",
        "Stay easy — nothing to prove here.": "放轻松——这里无需证明什么。",
        "Stay in control of the heat.": "有效控制热量。",
        "Stay quiet a few more minutes.": "再安静几分钟。",
        "Stay soft in the poses.": "保持体式时的柔软。",
        "Stay soft through each pose — nothing to prove.": "在每个体式中保持柔软——无需证明什么。",
        "Stay soft until the planned time is done.": "在预定时间结束前保持柔软。",
        "Stay soft — nothing to push.": "保持柔软——无需施压。",
        "Stay with the breath for another \\(minutesPhrase(remaining)) minutes.": "再保持呼吸\\(minutesPhrase(remaining))分钟。",
        "Stay with the breath until the planned time is done.": "保持呼吸，直至预定时间结束。",
        "Stay with the plan and keep the basics steady.": "坚持既定计划，牢牢把握基本原则。",
        "Staying with your existing plan is a reasonable default when you feel okay.": "如果您感觉状态良好，继续采用现有方案不失为一个合理的默认选择。",
        "Steady day": "稳定日",
        "Steady footing and early fluids beat hero pace.": "稳健的步伐与及时的补给，胜过英雄般的速度。",
        "Steady pace, early fuel, and leave margin for the way back.": "保持匀速前进，提前补充燃料，并为返程留出余地。",
        "Steady sleep duration": "稳定的睡眠时长",
        "Step out at the first sign of lightheadedness.": "一旦出现头晕迹象，请立即离开。",
        "Still in HIIT on a stacked day — keep intervals honest.": "仍在 HIIT 训练日——保持间歇训练的严格性。",
        "Still pedaling after a full day — you're in the thick of it.": "一整天后仍在继续骑行——你正处于最激烈的节奏之中。",
        "Still running on a stacked day — legs are doing real work.": "今天依然状态火热——双腿正全力以赴地发力。",
        "Still swimming after a full day — steady strokes count.": "一整天后仍在游泳——稳定的划水节奏至关重要。",
        "Strength block is next — prime the body, not the ego.": "接下来是力量训练——聚焦身体，而非自我。",
        "Strength is next — recovery isn't fully back yet.": "接下来是力量恢复——恢复尚未完全到位。",
        "Strength is next — the body isn't topped up, so ease in.": "接下来是力量训练——身体尚未补充能量，因此请放慢节奏。",
        "Strength next": "下一步：力量训练",
        "Strength work is banked — muscles need quiet now.": "力量训练已暂停——肌肉现在需要静养。",
        "Strength work is banked — repair starts now.": "强度修复工作已暂停——修复工作现已启动。",
        "Strength work is live — reps and sets are under load.": "力量训练处于实战状态——每组次数与组数均在负重下进行。",
        "Stretch ahead": "继续前行",
        "Stretch block is next — ease in from the first minute.": "接下来是拉伸块——从第一分钟起逐渐放松。",
        "Stretch block wrapped — stay soft a few minutes.": "将拉伸块包裹好——静置数分钟以保持柔软。",
        "Stretch calves and hips for ten minutes.": "拉伸小腿与臀部，持续十分钟。",
        "Stretch day is closing — protect the calm tonight.": "拉伸日即将结束——今晚请守护内心的平静。",
        "Stretch is live — ease into each hold without forcing.": "拉伸练习已开启——无需勉强，循序渐进地进入每个固定姿势。",
        "Stretch or walk briefly, then eat when hungry.": "先拉伸或短暂散步，然后在饥饿时进食。",
        "Stretch or walk briefly, then refuel if needed.": "拉伸或短暂散步，如有需要，请补充能量。",
        "Stretch session is live — ease into each hold.": "拉伸练习已开启——循序渐进地进入每个保持动作。",
        "Stretch what you trained for ten minutes.": "将您训练过的部位拉伸十分钟。",
        "Stretching is done — keep the softness.": "完成拉伸动作——保持柔软度。",
        "Suggested focus: \\(title.english)": "建议关注点：\\(title.english)",
        "Support readiness": "支持就绪状态",
        "Swim done": "游泳结束",
        "Swim is ahead — recovery isn't fully back yet.": "游泳运动已领先——但复苏尚未完全恢复。",
        "Swim is ahead — the body isn't topped up, so ease in.": "游泳阶段已过半——身体尚未充血，可稍作放松。",
        "Swim is banked — recovery is the job now.": "游泳已不再是首要任务——现在的重点是康复。",
        "Swim is coming — settle into a steady stroke early.": "游泳训练即将开始——尽早养成稳定的泳姿。",
        "Swim is done — shoulders are still warm from the water.": "游泳结束了——肩膀仍因浸水而温热。",
        "Switch to recovery mode now; sleep will do more than another effort.": "立即切换至恢复模式；进入睡眠状态比再次尝试更为有效。",
        "TOMORROW": "明天",
        "Take a 10-minute walk or stretch before the day fills in.": "在白天到来之前，先散散步或做做拉伸运动，花上10分钟时间。",
        "Take a 10-minute walk or stretch, then pick today's first block.": "先步行或拉伸10分钟，然后选择今天的第一街区。",
        "Take five quiet minutes before your next block.": "在开始下一个工作时段前，先静置五分钟。",
        "Take the full rest — then the next set with clean form.": "先完全休息，然后以正确的姿势进行下一组训练。",
        "Take twenty quiet minutes — walk, stretch, or lie down.": "花上二十分钟静下来——散步、拉伸或躺下。",
        "Tempo Run": "节奏跑",
        "Ten easy minutes on court — let body and pulse land.": "在球场上简单活动十分钟——让身体和脉搏自然恢复。",
        "Ten easy minutes, then refuel and rehydrate.": "只需十分钟，然后补充能量并补充水分。",
        "Ten minutes easy — slow enough to talk.": "十分钟轻松完成——速度足够慢，足以让人交谈。",
        "Ten minutes mobility, then your opening sets.": "先进行十分钟热身活动，接着进行开练环节。",
        "Ten quiet minutes, then pick one priority.": "静默十分钟，然后选定一项优先事项。",
        "Thanks — noted for your timeline.": "谢谢——已记录您的时间线。",
        "The current workout is already creating enough load.": "目前的训练强度已经足以产生足够的负荷。",
        "The current workout is already creating enough load. The useful move now is keeping quality until the finish.": "当前的训练强度已足以产生足够的负荷。现阶段的关键在于直至训练结束，始终保持动作质量。",
        "The day does not need a correction right now. A steady rhythm is more useful than adding another task.": "此刻并不需要进行调整。保持稳定的节奏，比增加一项新任务更为有益。",
        "The day is open enough to stay simple.": "这一天足够简单，无需复杂。",
        "The day starts here — follow the plan at your pace.": "新的一天从这里开始——按照自己的节奏，遵循计划前行。",
        "The main signals do not ask for a correction right now.": "主要信号目前并未要求修正。",
        "The most useful move now is letting the day come down.": "眼下最明智的做法，就是让这一天过去。",
        "The next workout will go better if you arrive settled instead of spending energy too early.": "如果你提前调整好状态再开始训练，而不是过早消耗体力，接下来的训练效果会更好。",
        "The rallies are hot — use the next changeover to settle.": "市场情绪高涨——趁下一轮行情波动时果断平仓。",
        "The run is already live. Keep effort easy, avoid adding intensity, and finish with reserve.": "本次跑步训练已正式开始。请保持轻松节奏，避免增加强度，并以储备力收尾。",
        "The run is already live. Recovery is shaping the effort ceiling, so easy pacing and reserve matter most now.": "本次跑步活动已正式开启。体能恢复正在决定本次活动的强度上限，因此现阶段保持轻松配速并保留体能储备至关重要。",
        "The training signal is already in. Recovery now matters more than adding load.": "训练信号已到位，此时恢复的重要性已超越增加负荷。",
        "The useful move now is making the evening quieter so sleep can do its job.": "现在最好的做法是让夜晚变得更安静，好让睡眠能尽到它的作用。",
        "The walk has already helped the body ease out of load.": "步行已有助于身体逐步卸除负荷。",
        "The walk is already in — the day can settle calmly.": "散步已然开始——这一天终于可以平静地结束了。",
        "The walks already helped things settle.": "散步已经有助于让情况趋于稳定。",
        "The walks helped things settle — keep the evening calm.": "散步有助于让心境平静下来——让夜晚保持宁静。",
        "The work is banked — now close the day calmly.": "工作已告一段落——现在，平静地结束这一天吧。",
        "The work is done — sleep is the only job left.": "工作已经做完——睡眠成了唯一剩下的“工作”。",
        "The workout is already live. Movement quality, technique, and reserve matter more than max effort now.": "本次训练已正式开启。现阶段，动作质量、技术执行及体能储备比最大努力更为重要。",
        "There isn’t enough consistent evidence for a weekly focus yet.": "目前尚无足够的一致性证据支持每周一次的聚焦做法。",
        "There isn’t enough planned vs completed activity in the last 7 days to talk about consistency yet.": "过去 7 天内，计划中的活动与已完成活动的数量尚不足以支撑对一致性的讨论。",
        "There isn’t enough recent data to compare yet.": "目前尚无足够的最新数据进行比较。",
        "There isn’t enough recent sleep, HRV, or resting heart rate data available to personalize this yet.": "近期睡眠、HRV 或静息心率数据还不够，暂时无法更贴合你。",
        "There isn’t enough recent sleep, HRV, or resting heart rate data to describe recovery yet.": "目前尚无足够的近期睡眠、 HRV 或静息心率数据来描述恢复情况。",
        "There isn’t enough sleep or HRV across the last 7 days to summarize yet.": "过去7天内，睡眠或 HRV 时长均不足以做出总结。",
        "There isn’t enough sleep or HRV logged across the last 7 days to summarize yet.": "过去7天内，睡眠时长或 HRV 记录均不足，尚无法进行总结。",
        "There’s no nutrition log available yet for today. You can add meals anytime, or open Meal Builder when you’re ready.": "今日暂无营养记录可用。您可随时添加餐食，或在准备就绪时打开「餐食创建器」。",
        "These are logged sessions only — not a judgement of training load.": "此处仅记录已登录的会话——并非对训练负荷的评估。",
        "This breath work is getting forced — slow it until it feels calm again.": "这次呼吸练习变得过于用力——请放慢节奏，直到感觉重新平静下来。",
        "This doesn’t change your Plan or today’s Coach recommendation.": "这不会改变您的计划或今日教练的建议。",
        "This doesn’t judge whether intake was adequate overall.": "这并不对整体摄入量是否充足做出评判。",
        "This hike is running hotter than it needs to — today it still counts as recovery.": "这场徒步活动的热度已超出必要范围——尽管今天它仍被视作复苏阶段。",
        "This stretch is getting forced — ease out until it feels calm again.": "这个拉伸动作正在变得过于用力——请逐渐放松，直到感觉重新平静下来。",
        "This walk is running hotter than it needs to — today it still counts as recovery.": "这次步行活动的热度已超出必要范围——尽管今天它仍被视作恢复性活动。",
        "This yoga is getting forced — soften until it feels calm again.": "这个瑜伽动作正在被强行执行——先放松，直到感觉重新变得平静。",
        "Time for sleep": "该睡觉了",
        "Tired": "疲惫",
        "Today": "今天",
        "Today already has enough work in it — tomorrow needs fresh legs.": "今日已任重道远——明日更需注入新的活力。",
        "Today is better for recovery": "今天对康复更有利。",
        "Today is for recovery — keep the morning easy.": "今天是恢复之日——让清晨时光轻松惬意。",
        "Today's load is already banked, and tomorrow has a long 3.5-hour ride planned.": "今天的行程已经安排妥当，而明天的行程则计划进行一场长达 3.5 小时的长途骑行。",
        "Today's ride should stay below your normal ceiling.": "今天的骑行强度应控制在您平时的上限以下。",
        "Today's session should prioritize quality over load.": "本次会议应优先考虑质量而非工作量。",
        "Today’s plan is ready": "今天的计划已准备就绪。",
        "Today’s plan is ready.": "今天的计划已准备就绪。",
        "Tomorrow already has real work on the calendar.": "明天日程表上已经安排了实际工作。",
        "Tomorrow already has real work — keep today calm.": "明天已经有了实实在在的工作——今天请保持平静。",
        "Tomorrow brings your biggest effort — today is about arriving ready.": "明天将是你付出最大努力之日——而今天，则是要做好充分准备。",
        "Tomorrow carries real demand. Saving energy today protects the next training day.": "明天将面临切实的需求。今天节约能源，便是为下一个训练日保驾护航。",
        "Tomorrow has enough demand that adding load today would make it harder.": "明天的需求已足够大，若今天增加负载，反而会使情况更加困难。",
        "Tomorrow has real work on the calendar.": "明天日程表上有实际工作。",
        "Tomorrow needs fresh legs — sleep first.": "明天需要新的活力——先睡一觉。",
        "Tomorrow needs fresh legs — sleep gives more than another block.": "明天需要新的活力——睡眠带来的益处远不止多睡一个街区那么简单。",
        "Tomorrow needs fresh legs — sleep now.": "明天需要新的活力——现在好好休息。",
        "Tomorrow still needs fresh legs.": "明天仍需重新发力。",
        "Tomorrow's start depends on tonight": "明天的开端取决于今晚。",
        "Training is banked — energy is softer than usual.": "训练量已蓄积——体能较往常更为疲软。",
        "Training is banked — recovery is the job now.": "训练已暂告一段落——现在的首要任务是恢复。",
        "Training is done — the body is asking for margin, not more load.": "训练已完成——身体此时需要的是安全余量，而非增加负荷。",
        "Training is on the plan — recovery is lagging.": "训练按计划进行——但恢复进度滞后。",
        "Training is on the plan — start from how you feel now.": "训练计划已在制定中——从您当下的感受出发。",
        "Treat recovery as the plan for the rest of today.": "将康复视为今天剩余时间的应对方案。",
        "Treat small tasks as enough — recovery is part of the plan.": "将小任务视为已完成——恢复本就是计划的一部分。",
        "Treat the first 20 minutes as a systems check — start easier than usual.": "将最初的 20 分钟视为系统检查阶段——以比平时更简单的方式启动。",
        "Treat today as recovery first, training second.": "今天请将恢复置于首位，训练次之。",
        "Treating this as mainly last night — I’ll stick to today’s recovery signals.": "我将此情况主要视为昨晚的情况——接下来我将仅关注今日的反弹信号。",
        "Trust the feeling even when numbers are unclear. A short break or easier movement is enough for today.": "即使数据尚不明确，也请相信身体的直觉。今天只需短暂休息或进行一些轻松的活动即可。",
        "Try \\(titleEnglish) (\\(portionEnglish)) — about \\(proteinGrams) g protein and \\(calories) kcal. This isn’t logged yet.": "尝试\\(titleEnglish)(\\(portionEnglish)) —— 关于\\(proteinGrams)g 蛋白及\\(calories)kcal。此数据尚未记录。",
        "Twenty easy minutes — no pushing and no target.": "只需二十分钟——无需刻意推动，也无需设定目标。",
        "Twenty easy minutes — phone optional, pace low.": "仅需二十分钟——无需手机，节奏舒缓。",
        "Under load": "负载状态下",
        "Understood. Recovery or today’s plan — what should we look at?": "明白。关于恢复计划或今日计划——我们应当关注哪些方面？",
        "Upper body is live — control the weight on every rep.": "上肢保持发力状态——确保每次重复动作中体重控制得当。",
        "Upper body is next — shoulders and grip before weight.": "接下来是上肢训练——先练肩部和握力，再练负重训练。",
        "Use changeovers — towel off, one deep breath.": "进行转换时——脱去毛巾，深吸一口气。",
        "Use the morning for fuel, hydration, and an easy warmup walk.": "将早晨时间用于补充能量、补充水分，以及进行轻松的热身步行。",
        "Use the next changeover to reset breathing.": "利用下一次切换操作重置呼吸。",
        "Use the next recovery interval until breathing settles.": "使用下一个恢复间隔，直至呼吸恢复平稳。",
        "Use the walk to recover — easy steps, not more load.": "通过步行恢复体力——简单步骤，无需增加负担。",
        "Use today's recovery for calm movement or rest — intensity can wait.": "今日恢复训练可用于温和活动或休息——强度则可稍后安排。",
        "Vegetarian": "素食者",
        "WORKOUT": "健身训练",
        "Walk 15 minutes, then stretch before anything demanding.": "先步行15分钟，然后在进行高强度活动前进行拉伸。",
        "Walk 15 minutes, then stretch before planning anything hard.": "先散步15分钟，然后再进行拉伸，之后再进行高强度活动。",
        "Walk at a comfortable pace — easy enough to talk.": "以舒适的步速行走——速度要适中，方便交谈。",
        "Walk day — treat it as real movement, not filler.": "步行日——将其视为真正的运动，而非简单的填充活动。",
        "Walk five minutes before you stop moving.": "在停止活动前步行五分钟。",
        "Walk five minutes — let blood flow settle.": "步行五分钟——让血液流动趋于平稳。",
        "Walk is already in — keep a calm ordinary rhythm from here.": "步伐已然开启——从此起，保持一种平静而自然的节奏。",
        "Walk so you feel lighter after, not heavier.": "行走时，让你事后感觉更轻盈，而非更沉重。",
        "Walk ten minutes, then rest.": "步行十分钟，然后休息。",
        "Walk, stretch, or nap before anything demanding.": "在进行任何高强度活动前，请先散步、拉伸或小憩。",
        "Warm up 15 minutes — \\(title) at \\(time).": "热身 15 分钟 —\\(title)@\\(time)。",
        "Warm up first, then settle into the planned effort.": "先进行热身，然后进入既定状态的专注状态。",
        "Warm up joints and first sets light — form first.": "活动关节，先进行热身——先掌握基本姿势。",
        "Warm up shoulders and feet — controlled first games.": "热身肩部与足部——进行有控制的初步练习。",
        "Warm up — first games under control.": "热身——前几场比赛已掌控局面。",
        "Water and a small snack before you start.": "开始前请饮用清水并食用少量零食。",
        "Water and a snack, 10-minute warmup — \\(titleEN) at \\(time).": "饮水与零食，10分钟热身——\\(titleEN)@\\(time)。",
        "Water by feel — first meal at your usual time.": "凭感觉饮水——在惯常时间享用第一餐。",
        "Water first — shoulders when breathing settles.": "先补水——待呼吸平稳后，再活动肩部。",
        "Water is running behind today.": "今天后面有水流。",
        "Water still behind.": "水仍滞留。",
        "We still hear that you feel \\(feeling.bilingualTitle.english.lowercased()). Missing for a fair comparison: \\(missingEN).": "我们仍听到您提到您感觉有\\(feeling.bilingualTitle.english.lowercased()）。但为了进行公平比较，仍缺少\\(missingEN)。",
        "We won’t claim a personal pattern from one or two check-ins. Over time, your timeline can show feelings next to relevant measurements.": "我们不会仅凭一两次签到数据就得出个人规律性结论。随着时间的推移，您的时间线将能在相关指标旁显示相应情绪变化。",
        "What are you noticing most?": "你最明显的感觉是什么？",
        "What are you noticing?": "你注意到了什么？",
        "What could I try today?": "今天我可以尝试些什么？",
        "What else do you want to look at?": "还想看什么？",
        "What shall we start with?": "我们从哪里开始？",
        "What should I focus on next week?": "下周我应该注意什么？",
        "What should we look at in your activity log?": "想看活动记录里的哪一块？",
        "What would help with food today?": "今天饮食上想看哪一块？",
        "What’s left": "还剩多少",
        "What’s your body telling you now?": "身体现在在告诉你什么？",
        "When the next session starts, check in how you feel and stay steady.": "下次课程开始时，请检查自己的感受，并保持心态平稳。",
        "Which days had shorter sleep?": "哪些天的睡眠时间较短？",
        "Why": "为什么",
        "Why this matters": "为何这至关重要",
        "Wind down": "放慢节奏",
        "Wind down now — sleep carries tomorrow's legs.": "现在该休息了——睡眠将为明日提供支撑。",
        "Wind down now — sleep is the work.": "现在该放松了——睡眠才是最重要的事。",
        "Wind down — sleep is the priority.": "逐渐放松——睡眠是首要任务。",
        "Wind down — sleep is the work.": "逐渐放松——睡眠便是工作。",
        "Wind down — sleep is where strength settles in.": "逐渐放松——睡眠正是体力得以恢复之时。",
        "Wind the day down": "为这一天画上句号",
        "Work is done — protect sleep tonight.": "工作已毕——今晚好好休息。",
        "Work the effort, then reset.": "尽力操作，然后重置。",
        "Workout distribution across \\(active.count) active days.": "\\(active.count)活跃天数内的训练分布情况。",
        "Workouts: \\(totalSessions(current)) now vs \\(totalSessions(previous)) before.": "训练对比：\\(totalSessions(current)) 当前 vs\\(totalSessions(previous)) 之前。",
        "Yes": "是",
        "Yesterday still counts — go easier today.": "昨天依然重要——今天请放轻松。",
        "Yesterday still counts — today's plan stays measured.": "昨日依然重要——今日的计划仍保持审慎。",
        "Yesterday was heavy — recovery looks normal today.": "昨天情况很严重——今天的恢复情况看起来正常。",
        "Yesterday we discussed a lighter session. Did you get a chance to do it?": "昨天我们讨论了一个轻量版环节。你有机会参与吗？",
        "Yesterday's load is still in the legs — keep the evening easy.": "昨天的工作量仍集中在腿部——今晚请保持轻松。",
        "Yesterday's load is still in the legs — recovery matters more now.": "昨天的训练负荷依然集中在下肢——如今恢复更为关键。",
        "Yesterday's load is still in the legs — today needs a softer line.": "昨天的负荷仍集中在腿部——今天的负荷则需要更柔和的线路。",
        "Yesterday's load landed — let today close calmly.": "昨日的任务已完成——愿今日能平静收官。",
        "Yesterday's training load is logged — keep the morning easy.": "昨日的训练负荷已记录——祝您上午轻松愉快。",
        "Yoga ahead": "瑜伽练习",
        "Yoga day is closing — protect the calm tonight.": "瑜伽日即将结束——今晚请守护内心的宁静。",
        "Yoga is done — carry the calm forward.": "瑜伽练习已完成——将平静延续至前方。",
        "Yoga is live — slow and present.": "瑜伽是当下的——缓慢而真切。",
        "Yoga is live — stay soft and present in each pose.": "瑜伽正在进行——在每一个体式中都保持柔软，全然投入当下。",
        "Yoga is next — arrive soft, not already tight.": "接下来是瑜伽——以轻柔的姿态进入，而非先感到紧绷。",
        "Yoga just ended — let the calm linger.": "瑜伽课刚刚结束——让这份宁静久久萦绕。",
        "You already logged activity today. How demanding did that session feel?": "您今天已经记录了活动。这次操作体验如何？",
        "You cleared the morning adjustment — that’s fine. Here’s what still matters today.": "您已完成上午的调整——这没问题。以下是今天仍需关注的事项。",
        "You completed \\(countText.english) (\\(durationText.english)) — \\(absDelta) fewer than before.": "您完成的\\(countText.english)（\\(durationText.english)）—\\(absDelta)数量少于之前。",
        "You completed \\(countText.english) (\\(durationText.english)) — \\(delta) more than before.": "您完成\\(countText.english)（\\(durationText.english)）—\\(delta)的次数比以往更多。",
        "You completed \\(countText.english), the same as before (\\(durationText.english)).": "您已完成\\(countText.english)，与之前（\\(durationText.english)）相同。",
        "You haven't logged a meal today, so there's no need to push the intensity yet.": "你今天还没有记录进食量，所以暂时无需增加运动强度。",
        "You logged a bit less activity than \\(previousPhrase.english).": "您的活动记录量略少于\\(previousPhrase.english)。",
        "You logged a bit more activity than \\(previousPhrase.english).": "您记录的活动次数比\\(previousPhrase.english)略多。",
        "You logged a workout today. Based on your food entries, there’s still protein left toward your daily goal. Want an idea for your next meal?": "您今天记录了一次锻炼。根据您记录的饮食信息，您的每日蛋白质摄入目标仍尚有缺口。需要下一餐的饮食建议吗？",
        "You logged an \\(phrase.en) today. How demanding did that session feel?": "您今天完成了\\(phrase.en)训练。这次训练感觉有多具挑战性？",
        "You logged more than one activity today. Which session should we talk about?": "您今天记录了不止一项活动。我们应该讨论哪一次会话？",
        "You noted: \\(clarification.bilingualTitle.english).": "您已注明：\\(clarification.bilingualTitle.english)。",
        "You slept less than usual after yesterday’s demanding session. A lighter workout may feel more manageable today. Want to review today’s plan?": "在经历了昨天高强度训练后，你的睡眠时间比平时少了一些。今天可以尝试强度稍低的训练，可能会感觉更容易应对。想回顾一下今天的训练计划吗？",
        "You slept less than usual after yesterday’s demanding session. Want a few recovery tips?": "昨天的高强度训练后，你的睡眠时间比平时少了。需要一些恢复建议吗？",
        "You slept less than usual last night.": "昨晚睡得比平时少。",
        "You slept less than usual last night. Want recovery tips, or to check today’s plan?": "昨晚您比平时睡得少。需要一些恢复建议，还是想查看今天的计划？",
        "You were a bit less active recently.": "最近你的活动量稍微减少了一些。",
        "You were a bit more active recently.": "你最近活动得稍微多了一些。",
        "You're behind on hydration, so keeping this session easy is the better call.": "你的水分补充不足，因此本次训练选择轻量强度更为合适。",
        "You're in HIIT — work the intervals, recover between.": "你已进入 HIIT 模式——进行间歇训练，并在间歇期恢复。",
        "You're in Zone 1 — recovery effort.": "您处于区域 1 —— 恢复阶段。",
        "You're in Zone 2 — aerobic work.": "您目前处于 Zone 2 —— 有氧运动区间。",
        "You're in Zone 3 — tempo effort.": "您已进入第三区——节奏强度区。",
        "You're in Zone 4 — hard effort, stay controlled.": "你已进入 Zone 4 —— 全力以赴，保持掌控。",
        "You're in Zone 5 — max effort, protect the rest of this session.": "你已进入 Zone 5 —— 全力以赴，守护本次训练的其他环节。",
        "You're in a \\(hoursEN) hike — protect the second half now.": "你正处于\\(hoursEN)徒步阶段——现在就开始保护后半段行程。",
        "You're in the heat — body works hard without moving.": "你正处于高温环境下——身体在不移动的情况下仍在剧烈工作。",
        "You're in the match — every point counts now.": "你已经进入比赛阶段——现在每一分都至关重要。",
        "You're in the run — \\(lowercaseFirst(en))": "你已进入冲刺阶段 —\\(lowercaseFirst(en))",
        "You're in the run — miles are ticking.": "你已进入冲刺阶段——时间一分一秒地流逝。",
        "You're in the water — \\(lowercaseFirst(en))": "您已入水 —\\(lowercaseFirst(en))",
        "You're in the water — the swim is live.": "你已入水——游泳比赛正式开始。",
        "You're on court — squash rewards patience point by point.": "你已踏上球场——壁球运动讲究一分一分地保持耐心。",
        "You're on the bike — \\(lowercaseFirst(en))": "你正在骑车上 —\\(lowercaseFirst(en))",
        "You're on the bike — the ride is live.": "您已登上自行车——骑行直播现已开启。",
        "You're partway through — keep this hike easy.": "你已走到中途——请保持轻松的徒步节奏。",
        "You're right where you should be — keep going.": "你已处于正确的位置——继续前行。",
        "You're right where you should be.": "你已来到该去的地方。",
        "Your activity level stayed fairly steady.": "您的活动水平保持相对稳定。",
        "Your activity was spread across \\(activeDays) days.": "您的活动分布在\\(activeDays)天内。",
        "Your average recorded sleep was \\(sleepText.english) — about \\(deltaMinutes) minutes longer than before.": "您平均记录的睡眠时长为\\(sleepText.english)分钟——较此前增加了约\\(deltaMinutes)分钟。",
        "Your average recorded sleep was \\(sleepText.english) — about \\(shorter) minutes shorter than before.": "您平均记录的睡眠时长为\\(sleepText.english)分钟——较此前缩短了约\\(shorter)分钟。",
        "Your average recorded sleep was \\(sleepText.english), similar to before.": "您的平均记录睡眠时长为\\(sleepText.english)，与之前相当。",
        "Your body will get more from recovery than from extra load right now.": "目前，你的身体从恢复中获得的益处将多于从额外负荷中获得的益处。",
        "Your data shows similar signals.": "您的数据也显示出类似的信号。",
        "Your numbers don’t fully explain how you feel.": "你的数据并不能完全解释你的感受。",
        "Your recorded sleep and recovery don’t fully explain how you feel.": "您记录的睡眠与恢复情况，并不能完全解释您的实际感受。",
        "Your recorded sleep and recovery don’t fully explain it.": "您记录的睡眠与恢复情况并不能完全解释这一现象。",
        "Your recovery is below your usual range today, even though you’re feeling good.": "尽管您感觉良好，但您今天的恢复情况仍低于您的常规范围。",
        "Your recovery is below your usual range today.": "今天恢复低于你平时的范围。",
        "Your recovery looks in good shape for you today.": "今天你的恢复看起来不错。",
        "Your reported feeling still stands. Metrics can miss stress, illness, travel, or simply a quiet day — we don’t have enough to identify a pattern from this alone.": "您报告的感受依然成立。相关指标可能无法捕捉到压力、疾病、旅行或仅仅是平静的一天——仅凭这些指标，我们尚不足以识别出某种规律。",
        "Your sleep and recovery look close to usual.": "睡眠和恢复都接近平时。",
        "You’re all set.": "您已准备就绪。",
        "You’ve already walked about \\(walkMinutes) minutes today — another short walk probably isn’t what you need.": "你今天已经走了约\\(walkMinutes)分钟——再来一次短途散步可能并不符合你的需求。",
        "You’ve got \\(label) on today’s plan, and nothing logged yet.": "您今天的计划中包含\\(label)，但目前尚未记录任何内容。",
        "You’ve logged \\(Int(nutrition.caloriesCurrent.rounded())) kcal and \\(Int(nutrition.proteinCurrent.rounded())) g protein so far. Set a goal to see what’s left.": "您目前已摄入\\(Int(nutrition.caloriesCurrent.rounded())) kcal 热量及\\(Int(nutrition.proteinCurrent.rounded())) g 蛋白质。设定一个目标，看看还剩多少。",
        "Zone 1 (\\(range)) — \\(effortEN). Easy pace is fine.": "区域 1 (\\(range)) —\\(effortEN)。轻松节奏即可。",
        "Zone 1 — easy.": "区域 1 — 简单。",
        "Zone 2 (\\(range)) — \\(effortEN). Hold this conversational pace.": "区域 2 (\\(range)) —\\(effortEN)。保持这种对话节奏。",
        "Zone 2 — aerobic.": "区域 2 — 有氧区。",
        "Zone 3 (\\(range)) — \\(effortEN). Stay controlled; don't drift higher.": "第 3 区（\\(range)）—\\(effortEN)。保持控制；切勿向上漂移。",
        "Zone 3 — tempo.": "区域 3 — 时间。",
        "Zone 4 (\\(range)) — \\(effortEN). Ease back a notch and hold.": "第 4 区 (\\(range)) —\\(effortEN)。将档位向后移动一格并固定。",
        "Zone 4 — hard, ease back.": "第 4 区 — 困难，可稍减强度。",
        "Zone 5 (\\(range)) — \\(effortEN). Ease off until breathing settles.": "第 5 区（\\(range)）—\\(effortEN)。逐渐减轻，直至呼吸平稳。",
        "Zone 5 — max, ease off.": "第 5 区 — 最大强度，逐渐减弱。",
        "\\(ack.english) What shall we start with?": "\\(ack.english)我们该从什么开始？",
        "\\(ack.english) \\(mind.english)": "（组合）\\(ack.chinese) \\(mind.chinese)",
        "\\(ack.english) \\(observation.english) \\(mind.english)": "（组合）\\(ack.chinese) \\(observation.chinese) \\(mind.chinese)",
        "\\(count) activities": "\\(count)活性",
        "\\(count) recovery sessions": "\\(count)恢复训练课",
        "\\(count) workouts": "\\(count)训练计划",
        "\\(countLabel.english) in the last 7 days": "过去 7 天内\\(countLabel.english)的出现情况",
        "\\(countLabel.english) · \\(durationText.english)": "（组合）\\(countLabel.chinese) · \\(durationText.chinese)",
        "\\(countLabel.english) · \\(durationText.english) total": "\\(countLabel.english)·\\(durationText.english)总计",
        "\\(current) g protein today — your recovery is usually better on training days around \\(rangeLow)–\\(rangeHigh) g. You're about \\(gap) g below that range.": "今天蛋白质 \\(current) g——训练日通常在 \\(rangeLow)–\\(rangeHigh) g 恢复更好。你大约还差 \\(gap) g。",
        "\\(day.completedSessionCount) · \\(AskCoachCopy.durationHoursMinutes(totalMinutes: day.completedDurationMinutes).english)": "（组合）\\(day.completedSessionCount) · \\(AskCoachCopy.durationHoursMinutes(totalMinutes: day.completedDurationMinutes).chinese)",
        "\\(evidence.recentActivityCount) logged activities in the last \\(evidence.activityWindowHours)h (context only — not a load score).": "\\(evidence.recentActivityCount)在过去\\(evidence.activityWindowHours)小时内记录了相关活动（仅用于上下文分析——并非负载评分）。",
        "\\(facts.todayActivityCount) sessions planned today.": "今日已安排\\(facts.todayActivityCount)会议。",
        "\\(feeling.bilingualTitle.english) · \\(clarification.bilingualTitle.english)": "（组合）\\(feeling.bilingualTitle.chinese) · \\(clarification.bilingualTitle.chinese)",
        "\\(hours)h": "\\(hours)小时",
        "\\(hours)h \\(mins)m": "\\(hours)小时 \\(mins)分钟",
        "\\(hours)h \\(minutes)m": "\\(hours)小时 \\(minutes)分钟",
        "\\(label): \\(count) · \\(duration.english)": "（组合）\\(label)：\\(count) · \\(duration.chinese)",
        "\\(label): \\(sleep.english)": "（组合）\\(label)：\\(sleep.chinese)",
        "\\(lead.en), \\(name). How are you feeling today?": "\\(lead.zh)，\\(name)。你今天感觉怎么样？",
        "\\(lead.en). How are you feeling today?": "\\(lead.zh)。你今天感觉怎么样？",
        "\\(metricEnglish) recorded for \\(observed) of \\(total) days": "\\(metricEnglish) 记录了 \\(observed)/\\(total) 天",
        "\\(mins)m": "\\(mins)分钟",
        "\\(minutes)m": "\\(minutes)分钟",
        "\\(name) — quick check-in. How’s your body feeling?": "\\(name)——快速确认一下。身体感觉如何？",
        "\\(name), what’s your body telling you now?": "\\(name)，身体现在在告诉你什么？",
        "\\(opener.english) \\(tail.english)": "（组合）\\(opener.chinese) \\(tail.chinese)",
        "\\(phrase) I’ll help you stay on track.": "\\(phrase) 我会帮你保持节奏。",
        "\\(previousNoun.english.capitalized): \\(previousActive) active days": "\\(previousNoun.chinese)：\\(previousActive) 个活跃日",
        "\\(primary.english) \\(detail.english)": "（组合）\\(primary.chinese) \\(detail.chinese)",
        "\\(title) at \\(activity.formattedStartTime) — prep from \\(prepStartTime(activity, leadMinutes: 15)).": "\\(title) 在 \\(activity.formattedStartTime)——从 \\(prepStartTime(activity, leadMinutes: 15)) 开始准备。",
        "\\(title) later at \\(activity.formattedStartTime).": "\\(title) 稍后在 \\(activity.formattedStartTime)。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — arrive calm, not already chasing.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——冷静到位，别一上来就追。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — dial in effort before the first mile.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——先把强度定稳，再开始第一英里。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — not fully topped up yet.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——状态还没完全恢复。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — recovery is still lagging.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——恢复仍偏慢。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — settle into a steady stroke early.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——尽早找到稳定的划水节奏。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — short sleep, recovery not full yet.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——睡眠偏短，恢复还没到位。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — time to settle pace and legs.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——先把配速和双腿稳定下来。",
        "\\(titleEN) \\(minutesEN) (\\(durationClauseEN)) — warm up before the first hard interval.": "\\(titleEN) \\(minutesEN)（\\(durationClauseEN)）——第一组高强度前先热身。",
        "\\(titleEN) \\(minutesEN) — \\(activity.formattedStartTime) on the clock.": "\\(titleEN) \\(minutesEN)——\\(activity.formattedStartTime) 开始。",
        "\\(titleEN) \\(minutesEN) — start easier than planned.": "\\(titleEN) \\(minutesEN)——比计划更轻松地开始。",
        "last week": "上周",
        "no logged activities": "没有已记录的活动",
        "the previous 28 days": "过去 28 天",
        "Activity, nutrition, or recovery?": "活动、营养还是恢复？",
        "Allow Health access to personalize this.": "允许访问健康数据后，我可以更贴合你。",
        "Another check-in. How's energy right now?": "再确认一下。现在精力如何？",
        "Anytime — I'm here when you want another look.": "随时可以再来，想看的时候我都在。",
        "Anytime — I’m here when you want another look.": "随时可以再来，想看的时候我都在。",
        "Body feels heavy": "身体沉重",
        "Breath work": "呼吸练习",
        "Calories look on track.": "热量目前在目标附近。",
        "Compared with yesterday, today looks busier.": "和昨天比，今天看起来更忙。",
        "Compared with yesterday, today looks lighter.": "和昨天比，今天看起来更轻松。",
        "Deep sleep": "深睡",
        "Deep sleep looks a bit light.": "深睡有点偏少。",
        "Don't overheat": "别过热",
        "Ease the legs": "放松双腿",
        "Energized": "精力充沛",
        "Good afternoon": "下午好",
        "Good evening": "晚上好",
        "HRV": "HRV",
        "HRV is a bit lower than your recent baseline.": "HRV 比你最近的基线略低。",
        "Hard to focus": "很难集中注意力",
        "Health data isn't available yet.": "健康数据还不可用。",
        "Health data isn’t available yet.": "健康数据还不可用。",
        "Heart rate variability": "心率变异性（HRV）",
        "Heavy legs": "腿很沉",
        "Hold your pace": "保持节奏",
        "How are you feeling today?": "你今天感觉怎么样？",
        "How's your energy right now?": "你现在精力怎么样？",
        "I don't have enough activity data for a fair look.": "活动数据还不够，暂时不好比较。",
        "I don't have enough sleep data yet.": "我还没有足够的睡眠数据。",
        "I don't see meals logged yet today.": "今天还没有看到饮食记录。",
        "I don’t have enough activity data for a fair look.": "活动数据还不够，暂时不好比较。",
        "I don’t have enough sleep data yet.": "我还没有足够的睡眠数据。",
        "I don’t see meals logged yet today.": "今天还没有看到饮食记录。",
        "IMPORTANT": "重要",
        "Is this mostly about last night's sleep, or has it been building for a few days?": "主要是昨晚睡眠，还是这几天一直这样？",
        "Leave something": "留点余力",
        "Load over the last 7 days looks higher than usual.": "近 7 天的负荷比平时高。",
        "Load over the last 7 days looks manageable.": "近 7 天的负荷看起来可控。",
        "Low": "不太好",
        "Mentally drained": "脑子很累",
        "Nice work checking in.": "来确认一下状态，很好。",
        "No sessions logged yet today.": "今天还没有记录训练。",
        "Protect": "保护",
        "Protein is tracking well so far.": "目前蛋白质摄入不错。",
        "Quick check-in. How's your body feeling?": "快速确认一下。身体感觉如何？",
        "Ready": "状态良好",
        "Recent sleep, HRV, or resting heart rate readings aren't available yet — they may still be syncing, or weren't recorded.": "近期睡眠、HRV 或静息心率数据还不可用——可能仍在同步，或尚未记录。",
        "Recover": "恢复",
        "Recovery looks protected — keep today easier.": "恢复状态需要呵护——今天尽量轻松一些。",
        "Recovery signals look steady.": "恢复信号看起来平稳。",
        "Recovery time": "恢复时间",
        "Resting heart rate": "静息心率",
        "Resting heart rate is a bit higher than usual.": "静息心率比平时略高。",
        "Shall we look at activity, nutrition, or recovery?": "要看活动、营养还是恢复？",
        "Sleep": "睡眠",
        "Sleepy": "困倦",
        "Soft reset": "轻柔放松",
        "Sore": "酸痛",
        "Steady": "平稳",
        "Stressed": "压力大",
        "Stretch session": "拉伸训练",
        "Stretch time": "拉伸时间",
        "Stretching": "拉伸",
        "That's enough for now.": "今天先到这里。",
        "That’s enough for now.": "今天先到这里。",
        "There isn't enough recent sleep, HRV, or resting heart rate data available to personalize this yet.": "近期睡眠、HRV 或静息心率数据还不够，暂时无法更贴合你。",
        "There's still room before your calorie target.": "离热量目标还有一些空间。",
        "There’s still room before your calorie target.": "离热量目标还有一些空间。",
        "Today's plan": "今日计划",
        "Want a quick look anyway?": "还是想先快速看一眼？",
        "Want to look at sleep, training, or food?": "想看看睡眠、训练还是饮食？",
        "Water looks low so far.": "目前饮水量偏低。",
        "We can still talk about what you noticed.": "我们还是可以聊聊你注意到的情况。",
        "What's left": "还剩多少",
        "What's your body telling you now?": "身体现在在告诉你什么？",
        "Yoga": "瑜伽",
        "Yoga session": "瑜伽训练",
        "Yoga time": "瑜伽时间",
        "You already moved today.": "你今天已经活动过了。",
        "You're still short on protein for today.": "今天蛋白质还差一点。",
        "Your sleep last night looks shorter than usual.": "昨晚睡眠比平时短一些。",
        "Your sleep last night looks solid.": "昨晚睡眠看起来不错。",
        "You’re still short on protein for today.": "今天蛋白质还差一点。",
    ]
}
