#!/usr/bin/env python3
"""Add InsightsStoryEngine localization keys to Localizable.xcstrings."""
import json
from pathlib import Path

XCSTRINGS = Path(__file__).resolve().parents[1] / "WeekFit" / "Localizable.xcstrings"

TRANSLATIONS = {
    "insights.section.whyThisStory": ("WHY THIS STORY", "ПОЧЕМУ ЭТА ИСТОРИЯ"),
    "insights.section.trend": ("TREND", "ТРЕНД"),
    "insights.section.action": ("ACTION", "ДЕЙСТВИЕ"),
    "insights.section.recovery": ("RECOVERY", "ВОССТАНОВЛЕНИЕ"),
    "insights.section.activity": ("ACTIVITY", "АКТИВНОСТЬ"),
    "insights.section.nutrition": ("NUTRITION", "ПИТАНИЕ"),
    "insights.story.confidence.high": ("High Confidence", "Высокая уверенность"),
    "insights.story.confidence.medium": ("Medium Confidence", "Средняя уверенность"),
    "insights.story.confidence.low": ("Low Confidence", "Низкая уверенность"),
    "insights.story.type.change": ("Change story", "История изменений"),
    "insights.story.type.risk": ("Risk story", "История риска"),
    "insights.story.type.opportunity": ("Opportunity story", "История возможности"),
    "insights.story.type.anomaly": ("Anomaly story", "История аномалии"),
    "insights.story.type.plateau": ("Plateau story", "История плато"),
    "insights.story.type.maintenance": ("Maintenance story", "История поддержания"),
    "insights.story.sourceSummaryFormat": ("%@ • Impact %lld/100", "%@ • Влияние %lld/100"),
    "insights.story.timeframe.last30Days": ("Last 30 Days", "Последние 30 дней"),
    "insights.story.target.recovery72": ("72 target", "Цель 72"),
    "insights.story.target.sleep7h": ("7h target", "Цель 7 ч"),
    "insights.story.badge.recovery": ("Recovery", "Восстановление"),
    "insights.story.badge.average": ("average", "среднее"),
    "insights.story.badge.pattern": ("pattern", "паттерн"),
    "insights.story.badge.patterns": ("patterns", "паттерны"),
    "insights.story.badge.calPerDay": ("cal/day", "ккал/день"),
    "insights.story.badge.baseline": ("baseline", "базовый уровень"),
    "insights.signal.read": ("Read", "Сигнал"),
    "insights.signal.sleep": ("Sleep", "Сон"),
    "insights.signal.load": ("Load", "Нагрузка"),
    "insights.signal.protein": ("Protein", "Белок"),
    "insights.signal.recovery": ("Recovery", "Восстановление"),
    "insights.signal.activeCalories": ("Active calories", "Активные калории"),
    "insights.signal.recentTrend": ("Recent trend", "Недавний тренд"),
    "insights.signal.weekendGap": ("Weekend gap", "Разрыв выходных"),
    "insights.signal.hardDays": ("Hard days", "Тяжёлые дни"),
    "insights.signal.target7h": ("Target: 7h", "Цель: 7 ч"),
    "insights.signal.target6of7": ("Target: 6 of 7 days", "Цель: 6 из 7 дней"),
    "insights.signal.average": ("average", "среднее"),
    "insights.signal.recentBase": ("recent base", "недавняя база"),
    "insights.signal.aboveRecentBase": ("above recent base", "выше недавней базы"),
    "insights.signal.perDay": ("per day", "в день"),
    "insights.signal.vsBaseline": ("vs baseline", "к базовому уровню"),
    "insights.signal.vsWeekdays": ("vs weekdays", "к будням"),
    "insights.signal.recoveryPoints": ("recovery points", "баллы восстановления"),
    "insights.signal.targetDays": ("target days", "дней с целью"),
    "insights.signal.hydratedVsLowFluid": ("hydrated vs low-fluid", "с жидкостью vs мало жидкости"),
    "insights.signal.recent7Days": ("recent 7 days", "последние 7 дней"),
    "insights.signal.correlation.recovery": ("recovery", "восстановление"),
    "insights.signal.correlation.load": ("load", "нагрузка"),
    "insights.signal.load.recoveryWeek": ("Recovery Week", "Неделя восстановления"),
    "insights.signal.load.high": ("High Load", "Высокая нагрузка"),
    "insights.signal.load.solid": ("Solid Load", "Устойчивая нагрузка"),
    "insights.signal.load.base": ("Base Load", "Базовая нагрузка"),
    "insights.signal.value.noInsight": ("no insight", "нет инсайта"),
    "insights.signal.value.building": ("building", "формируется"),
    "insights.signal.value.flat": ("flat", "ровно"),
    "insights.signal.value.down": ("down", "ниже"),
    "insights.signal.detail.notEnoughSeparation": ("not enough separation", "недостаточно различий"),
    "insights.signal.detail.keepWatching": ("keep watching", "продолжайте наблюдать"),
    "insights.signal.detail.notEnoughData": ("not enough data", "недостаточно данных"),
    "insights.signal.detail.complete7Days": ("complete 7 days", "заполните 7 дней"),
    "insights.signal.detail.afterImprovement": ("after improvement", "после улучшения"),
    "insights.signal.benchmark.plateau": ("plateau", "плато"),
    "insights.action.viewRecoveryAnalysis": ("View Recovery Analysis", "Анализ восстановления"),
    "insights.action.reviewTrainingTrends": ("Review Training Trends", "Тренды тренировок"),
    "insights.action.exploreNutritionDetails": ("Explore Nutrition Details", "Детали питания"),
    "insights.action.openCoach": ("Open Coach", "Открыть Тренера"),
    "insights.action.logToday": ("Log Today", "Записать в Сегодня"),
    "insights.action.openNutrition": ("Open Nutrition", "Открыть Питание"),
    "insights.action.openPlan": ("Open Plan", "Открыть План"),
    "insights.action.reviewDetails": ("Review Details", "Подробнее"),
    "insights.story.outcome.restoreRecoveryMargin": ("restore recovery margin", "восстановить запас восстановления"),
    "insights.story.outcome.preserveRecoveryMargin": ("preserve recovery margin", "сохранить запас восстановления"),
    "insights.story.outcome.confirmRecoveryResponding": ("confirm recovery is responding", "убедиться, что восстановление реагирует"),
    "insights.story.outcome.confirmLoadSustainable": ("confirm the load is sustainable", "убедиться, что нагрузка устойчива"),
    "insights.story.outcome.makeRecoveryEasierToExplain": ("make recovery easier to explain", "сделать восстановление понятнее"),
    "insights.story.outcome.makeHardDayRecoveryEasier": ("make hard-day recovery easier to compare", "упростить сравнение восстановления в тяжёлые дни"),
    "insights.story.outcome.surfaceRankedInsight": ("surface a real ranked insight", "выявить реальный ранжированный инсайт"),
    "insights.story.outcome.surfaceNextChange": ("surface the next real change, risk, opportunity or anomaly", "выявить следующее реальное изменение, риск, возможность или аномалию"),
    "insights.story.outcome.unlockRankedInsight": ("unlock a real ranked insight", "открыть реальный ранжированный инсайт"),
    "insights.story.outcome.closeSleepGap": ("close the sleep-duration gap", "сократить разрыв по длительности сна"),
    "insights.story.outcome.letRecoveryCatchUp": ("let recovery catch up", "дать восстановлению догнать"),
    "insights.fallback.stable.hero.title": ("No dominant insight yet", "Пока нет главного инсайта"),
    "insights.fallback.stable.hero.subtitle": ("Recovery, sleep, activity and nutrition do not show a ranked change, risk, opportunity or anomaly.", "Восстановление, сон, активность и питание не показывают ранжированного изменения, риска, возможности или аномалии."),
    "insights.fallback.stable.hero.takeaway": ("Keep logging until a real pattern emerges.", "Продолжайте записывать данные, пока не проявится реальный паттерн."),
    "insights.fallback.stable.driver.title": ("No dominant insight", "Нет главного инсайта"),
    "insights.fallback.stable.driver.text": ("No change, risk, opportunity or anomaly is strong enough to rank yet.", "Ни одно изменение, риск, возможность или аномалия пока недостаточно сильны для ранжирования."),
    "insights.fallback.stable.action.title": ("Keep collecting signal", "Продолжайте собирать сигнал"),
    "insights.fallback.stable.action.text": ("surface the next real change, risk, opportunity or anomaly", "выявить следующее реальное изменение, риск, возможность или аномалию"),
    "insights.fallback.stable.action.action": ("Keep logging sleep, recovery, food and training for the next 7 days.", "Записывайте сон, восстановление, еду и тренировки следующие 7 дней."),
    "insights.fallback.baseline.hero.title": ("Building your patterns", "Формируем ваши паттерны"),
    "insights.fallback.baseline.hero.subtitle": ("Log sleep, meals, drinks and activities for a few more days to unlock trends.", "Записывайте сон, блюда, напитки и активность ещё несколько дней, чтобы открыть тренды."),
    "insights.fallback.baseline.hero.takeaway": ("Start with one consistent week.", "Начните с одной последовательной недели."),
    "insights.fallback.baseline.driver.title": ("Insufficient overlap", "Недостаточное пересечение данных"),
    "insights.fallback.baseline.driver.text": ("Insights needs more overlapping sleep, recovery, training and nutrition data before ranking stories.", "Инсайтам нужно больше пересекающихся данных о сне, восстановлении, тренировках и питании перед ранжированием историй."),
    "insights.fallback.baseline.action.title": ("Build a complete baseline", "Соберите полную базовую линию"),
    "insights.fallback.baseline.action.text": ("unlock a real ranked insight", "открыть реальный ранжированный инсайт"),
    "insights.fallback.baseline.action.action": ("Log sleep, meals, drinks and activity every day for the next 7 days.", "Записывайте сон, блюда, напитки и активность каждый день следующие 7 дней."),
    "insights.story.recovery.decline.titleHealthy": ("Recovery remains healthy but is declining", "Восстановление остаётся хорошим, но снижается"),
    "insights.story.recovery.decline.titleLosing": ("Recovery is losing momentum", "Восстановление теряет импульс"),
    "insights.story.recovery.decline.subtitleFormat": ("Recovery is down %lld points versus baseline.", "Восстановление ниже на %lld баллов относительно базового уровня."),
    "insights.story.recovery.decline.takeaway": ("Stabilize recovery before increasing load.", "Стабилизируйте восстановление перед увеличением нагрузки."),
    "insights.story.recovery.decline.action.sleepTitle": ("Restore sleep before increasing load", "Восстановите сон перед увеличением нагрузки"),
    "insights.story.recovery.decline.action.driverTitle": ("Stabilize the driver before adding load", "Стабилизируйте фактор перед добавлением нагрузки"),
    "insights.story.recovery.decline.action.sleepAction": ("Sleep at least 7 hours on 5 of the next 7 nights.", "Спите не менее 7 часов 5 из следующих 7 ночей."),
    "insights.story.recovery.decline.action.easyWorkouts": ("Keep every workout easy or Zone 2 for the next 7 days.", "Держите каждую тренировку лёгкой или в зоне 2 следующие 7 дней."),
    "insights.story.driver.sleepDuration.title": ("Sleep Duration", "Длительность сна"),
    "insights.story.driver.sleepDuration.belowRecovery": ("Sleep is below the level needed to protect recovery.", "Сон ниже уровня, необходимого для защиты восстановления."),
    "insights.story.driver.sleepDuration.belowTargetFormat": ("sleep is %.1fh below target, which reduces margin before load increases", "сон на %.1f ч ниже цели, что сокращает запас перед увеличением нагрузки"),
    "insights.story.driver.sleepDuration.gapDecliningFormat": ("sleep is %.1fh below target while recovery slipped %lld points", "сон на %.1f ч ниже цели, а восстановление упало на %lld баллов"),
    "insights.story.driver.sleepDuration.gapStableFormat": ("sleep is %.1fh below target, but recovery stayed %@ baseline", "сон на %.1f ч ниже цели, но восстановление осталось %@ базового уровня"),
    "insights.story.driver.sleepDuration.above": ("above", "выше"),
    "insights.story.driver.sleepDuration.near": ("near", "близко к"),
    "insights.story.driver.sleepConsistency.title": ("Sleep Consistency", "Стабильность сна"),
    "insights.story.driver.sleepConsistency.text": ("Sleep is at the level that supports recovery.", "Сон на уровне, который поддерживает восстановление."),
    "insights.story.driver.weekendSleep.title": ("Weekend Sleep", "Сон в выходные"),
    "insights.story.driver.weekendSleep.text": ("Weekend sleep is lower than weekdays.", "Сон в выходные ниже, чем в будни."),
    "insights.story.driver.trainingLoad.title": ("Training Load", "Тренировочная нагрузка"),
    "insights.story.driver.trainingLoad.outpacing": ("Training load is outpacing the recovery response.", "Тренировочная нагрузка опережает реакцию восстановления."),
    "insights.story.driver.trainingLoad.highStable": ("load is high, but recovery stayed above baseline", "нагрузка высокая, но восстановление осталось выше базового уровня"),
    "insights.story.driver.trainingLoad.outpacingShort": ("training load is outpacing the recovery response", "тренировочная нагрузка опережает реакцию восстановления"),
    "insights.story.driver.controlledLoad.title": ("Controlled Load", "Контролируемая нагрузка"),
    "insights.story.driver.controlledLoad.text": ("Training load has stayed controlled while recovery improved.", "Тренировочная нагрузка оставалась контролируемой, пока восстановление улучшалось."),
    "insights.story.driver.recoveryPlateau.title": ("Recovery Plateau", "Плато восстановления"),
    "insights.story.driver.recoveryPlateau.text": ("Recovery improved earlier, then flattened.", "Восстановление улучшилось раньше, затем выровнялось."),
    "insights.story.driver.recoveryConsistency.title": ("Recovery Consistency", "Стабильность восстановления"),
    "insights.story.driver.recoveryConsistency.text": ("Recovery itself is the clearest changed signal.", "Само восстановление — самый явный изменившийся сигнал."),
    "insights.story.driver.activeCalories.title": ("Active Calories", "Активные калории"),
    "insights.story.driver.activeCalories.text": ("Daily activity volume has fallen below baseline.", "Ежедневный объём активности упал ниже базового уровня."),
    "insights.story.driver.proteinConsistency.title": ("Protein Consistency", "Стабильность белка"),
    "insights.story.driver.proteinConsistency.text": ("Protein consistency is below the level needed to support adaptation.", "Стабильность белка ниже уровня, необходимого для адаптации."),
    "insights.story.driver.hydrationHardDays.title": ("Hydration on hard days", "Гидратация в тяжёлые дни"),
    "insights.story.driver.hydrationHardDays.text": ("Hydration is separating recovery after higher-load days.", "Гидратация разделяет восстановление после дней с высокой нагрузкой."),
    "insights.story.recovery.rebound.title": ("Recovery resilience is improving", "Устойчивость восстановления улучшается"),
    "insights.story.recovery.rebound.subtitleFormat": ("Recovery has rebounded %lld points versus baseline.", "Восстановление выросло на %lld баллов относительно базового уровня."),
    "insights.story.recovery.rebound.takeaway": ("Protect the routine that created the rebound.", "Защитите режим, который создал отскок."),
    "insights.story.recovery.rebound.action.sleepTitle": ("Protect the sleep routine", "Защитите режим сна"),
    "insights.story.recovery.rebound.action.loadTitle": ("Keep load increases gradual", "Увеличивайте нагрузку постепенно"),
    "insights.story.recovery.rebound.action.sleepAction": ("Keep sleep above 7 hours on 5 of the next 7 nights.", "Держите сон выше 7 часов 5 из следующих 7 ночей."),
    "insights.story.recovery.rebound.action.loadAction": ("Do not increase training volume by more than 10% over the next 7 days.", "Не увеличивайте объём тренировок более чем на 10% за следующие 7 дней."),
    "insights.story.recovery.plateau.title": ("Recovery plateau detected", "Обнаружено плато восстановления"),
    "insights.story.recovery.plateau.subtitle": ("Recovery improved, then stopped progressing.", "Восстановление улучшилось, затем перестало прогрессировать."),
    "insights.story.recovery.plateau.takeaway": ("Find the next limiter before adding load.", "Найдите следующий ограничитель перед добавлением нагрузки."),
    "insights.story.recovery.plateau.action.title": ("Hold volume while testing the next limiter", "Держите объём, проверяя следующий ограничитель"),
    "insights.story.recovery.plateau.action.action": ("Keep training volume flat for the next 7 days.", "Держите объём тренировок неизменным следующие 7 дней."),
    "insights.story.sleepPressure.trendLosingSupport": ("Recovery is starting to lose support", "Восстановление начинает терять поддержку"),
    "insights.story.sleepPressure.trendHoldingDespite": ("Recovery is holding despite short sleep", "Восстановление держится несмотря на короткий сон"),
    "insights.story.sleepPressure.subtitleDecliningFormat": ("Recovery is down %lld points while sleep is below target.", "Восстановление ниже на %lld баллов, пока сон ниже цели."),
    "insights.story.sleepPressure.subtitleStableFormat": ("Sleep is %.1fh vs a 7h target, but recovery has not dropped.", "Сон %.1f ч при цели 7 ч, но восстановление не упало."),
    "insights.story.sleepPressure.takeaway": ("Keep sleep above 7h before increasing training load.", "Держите сон выше 7 ч перед увеличением тренировочной нагрузки."),
    "insights.story.sleepPressure.action.title": ("Keep sleep above 7h before adding load", "Держите сон выше 7 ч перед добавлением нагрузки"),
    "insights.story.sleepPressure.action.action": ("keep sleep above 7h before adding load", "держите сон выше 7 ч перед добавлением нагрузки"),
    "insights.story.sleepBelowTarget.title": ("Sleep duration is below target", "Длительность сна ниже цели"),
    "insights.story.sleepBelowTarget.subtitleFormat": ("%.1fh average vs a 7h target.", "%.1f ч в среднем при цели 7 ч."),
    "insights.story.sleepBelowTarget.takeaway": ("Restore sleep before changing training load.", "Восстановите сон перед изменением тренировочной нагрузки."),
    "insights.story.weekendRecovery.title": ("Weekend recovery is weaker", "Восстановление в выходные слабее"),
    "insights.story.weekendRecovery.subtitleFormat": ("Weekend recovery is %lld points lower than weekdays.", "Восстановление в выходные на %lld баллов ниже, чем в будни."),
    "insights.story.weekendRecovery.takeaway": ("Protect weekend wake time.", "Защитите время пробуждения в выходные."),
    "insights.story.weekendRecovery.action.title": ("Protect weekend sleep timing", "Защитите режим сна в выходные"),
    "insights.story.weekendRecovery.action.action": ("Keep weekend wake time within 60 minutes of weekdays for the next 2 weekends.", "Держите время пробуждения в выходные в пределах 60 минут от будней следующие 2 выходных."),
    "insights.story.trainingLoad.trendAbsorbing": ("Recovery is absorbing high load", "Восстановление поглощает высокую нагрузку"),
    "insights.story.trainingLoad.trendNotKeepingUp": ("Recovery is not keeping up with load", "Восстановление не успевает за нагрузкой"),
    "insights.story.trainingLoad.subtitleStable": ("Load is high, but recovery stayed above baseline.", "Нагрузка высокая, но восстановление осталось выше базового уровня."),
    "insights.story.trainingLoad.subtitleRisk": ("Recovery is soft while training load is elevated.", "Восстановление слабое, пока тренировочная нагрузка повышена."),
    "insights.story.trainingLoad.takeawayStable": ("Confirm sustainability before adding load.", "Подтвердите устойчивость перед добавлением нагрузки."),
    "insights.story.trainingLoad.takeawayRisk": ("Hold training volume until recovery stabilizes.", "Держите объём тренировок, пока восстановление не стабилизируется."),
    "insights.story.trainingLoad.action.holdBeforeIncrease": ("Hold current load for 7 days before increasing", "Держите текущую нагрузку 7 дней перед увеличением"),
    "insights.story.trainingLoad.action.holdVolume": ("Hold current training volume", "Держите текущий объём тренировок"),
    "insights.story.trainingLoad.action.holdLoadAction": ("hold current load for 7 days before increasing", "держите текущую нагрузку 7 дней перед увеличением"),
    "insights.story.trainingLoad.action.noIncreaseAction": ("Do not add sessions or increase volume for the next 7 days.", "Не добавляйте сессии и не увеличивайте объём следующие 7 дней."),
    "insights.story.activeCalories.title": ("Active calories are declining", "Активные калории снижаются"),
    "insights.story.activeCalories.subtitle": ("Daily active calories are down versus baseline.", "Ежедневные активные калории ниже базового уровня."),
    "insights.story.activeCalories.takeaway": ("Rebuild activity consistency before adding intensity.", "Восстановите стабильность активности перед добавлением интенсивности."),
    "insights.story.activeCalories.action.title": ("Rebuild activity consistency", "Восстановите стабильность активности"),
    "insights.story.activeCalories.action.action": ("Complete 30 minutes of Zone 2 activity on 4 of the next 7 days.", "Выполняйте 30 минут активности зоны 2 4 из следующих 7 дней."),
    "insights.story.protein.trendWeaker": ("Recovery support is getting weaker", "Поддержка восстановления ослабевает"),
    "insights.story.protein.trendMissingSignal": ("Recovery is missing a nutrition signal", "Восстановлению не хватает сигнала питания"),
    "insights.story.protein.subtitleFormat": ("Protein target was hit on %lld of the last 7 logged days.", "Цель по белку достигнута %lld из последних 7 записанных дней."),
    "insights.story.protein.takeaway": ("Make protein consistent before changing training.", "Сделайте белок стабильным перед изменением тренировок."),
    "insights.story.protein.action.title": ("Use protein to support recovery", "Используйте белок для поддержки восстановления"),
    "insights.story.protein.action.action": ("Hit your protein target on at least 6 of the next 7 days.", "Достигайте цели по белку минимум 6 из следующих 7 дней."),
    "insights.story.hydration.title": ("Hard-day recovery is uneven", "Восстановление в тяжёлые дни неравномерное"),
    "insights.story.hydration.subtitleFormat": ("Recovery changes by %lld points based on hard-day hydration.", "Восстановление меняется на %lld баллов в зависимости от гидратации в тяжёлые дни."),
    "insights.story.hydration.takeaway": ("Prioritize fluids around hard training.", "Приоритизируйте жидкость вокруг тяжёлых тренировок."),
    "insights.story.hydration.action.title": ("Prioritize fluids around hard sessions", "Приоритизируйте жидкость вокруг тяжёлых сессий"),
    "insights.story.hydration.action.action": ("Drink at least 750ml in the 2 hours after each hard session this week.", "Пейте не менее 750 мл в течение 2 часов после каждой тяжёлой сессии на этой неделе."),
    "insights.domain.recovery.title": ("Recovery", "Восстановление"),
    "insights.domain.activity.title": ("Activity", "Активность"),
    "insights.domain.nutrition.title": ("Nutrition", "Питание"),
    "insights.domain.chartTargetRange": ("Target range", "Целевой диапазон"),
    "insights.domain.chartSustainableLoad": ("Sustainable load", "Устойчивая нагрузка"),
    "insights.domain.recovery.trend.needsAttention": ("Recovery needs attention", "Восстановлению нужно внимание"),
    "insights.domain.recovery.trend.resilient": ("Recovery remains resilient", "Восстановление остаётся устойчивым"),
    "insights.domain.recovery.trend.improving": ("Recovery is improving", "Восстановление улучшается"),
    "insights.domain.recovery.trend.stable": ("Recovery remains stable", "Восстановление остаётся стабильным"),
    "insights.domain.recovery.trend.needsSupport": ("Recovery needs support", "Восстановлению нужна поддержка"),
    "insights.domain.recovery.takeaway.sleepLower": ("Your recovery held up even while sleep was lower than usual.", "Восстановление держалось, даже когда сон был ниже обычного."),
    "insights.domain.recovery.takeaway.sleepVariability": ("Sleep variability is the main reason recovery looks less predictable.", "Изменчивость сна — главная причина, почему восстановление выглядит менее предсказуемым."),
    "insights.domain.recovery.takeaway.hrv": ("Improved HRV helped recovery stay steady under current load.", "Улучшенный ВСР помог восстановлению оставаться стабильным при текущей нагрузке."),
    "insights.domain.recovery.takeaway.rhr": ("Lower resting heart rate reduced strain and supported recovery.", "Более низкий пульс покоя снизил нагрузку и поддержал восстановление."),
    "insights.domain.recovery.takeaway.loadIncrease": ("Training pressure increased without creating a recovery drop.", "Тренировочное давление выросло без падения восстановления."),
    "insights.domain.recovery.takeaway.aligned": ("Sleep, HRV and resting heart rate stayed aligned enough to support your routine.", "Сон, ВСР и пульс покоя оставались достаточно согласованными для поддержки вашего режима."),
    "insights.domain.recovery.focus.recoveryDay": ("Add one recovery day.", "Добавьте один день восстановления."),
    "insights.domain.recovery.focus.sleepConsistency": ("Improve sleep consistency.", "Улучшите стабильность сна."),
    "insights.domain.recovery.focus.maintainLoad": ("Maintain current load.", "Поддерживайте текущую нагрузку."),
    "insights.domain.recovery.focus.maintainApproach": ("Maintain current approach.", "Поддерживайте текущий подход."),
    "insights.domain.recovery.signal.sleepSupports.label": ("Sleep supports recovery", "Сон поддерживает восстановление"),
    "insights.domain.recovery.signal.sleepSupports.healthy": ("Sleep stayed inside a healthy range.", "Сон оставался в здоровом диапазоне."),
    "insights.domain.recovery.signal.sleepSupports.opportunity": ("Sleep is the main opportunity to protect recovery.", "Сон — главная возможность защитить восстановление."),
    "insights.domain.recovery.signal.stabilized.label": ("Recovery stabilized", "Восстановление стабилизировалось"),
    "insights.domain.recovery.signal.stabilized.positive": ("Recent scores stopped declining.", "Недавние показатели перестали снижаться."),
    "insights.domain.recovery.signal.stabilized.negative": ("Recent scores are still losing some margin.", "Недавние показатели всё ещё теряют запас."),
    "insights.domain.recovery.signal.noOverload.label": ("No overload detected", "Перегрузка не обнаружена"),
    "insights.domain.recovery.signal.noOverload.resilient": ("Recovery stayed resilient under current load.", "Восстановление оставалось устойчивым при текущей нагрузке."),
    "insights.domain.recovery.signal.noOverload.absorbing": ("Recovery is absorbing a higher training load.", "Восстановление поглощает более высокую тренировочную нагрузку."),
    "insights.domain.recovery.validation.strongDespiteSoft": ("Recovery stayed strong despite softer signals", "Восстановление оставалось сильным несмотря на более слабые сигналы"),
    "insights.domain.recovery.validation.improvingNeedsSupport": ("Recovery is improving but needs support", "Восстановление улучшается, но нуждается в поддержке"),
    "insights.domain.recovery.validation.strongTakeaway": ("Recovery quality held while signals softened.", "Качество восстановления сохранилось, пока сигналы ослабли."),
    "insights.domain.recovery.validation.improvingTakeaway": ("Readiness is moving up but still has limited margin.", "Готовность растёт, но запас всё ещё ограничен."),
    "insights.domain.activity.trend.sustainableProgress": ("Sustainable progress", "Устойчивый прогресс"),
    "insights.domain.activity.trend.needsRestraint": ("Training needs restraint", "Тренировкам нужна сдержанность"),
    "insights.domain.activity.trend.baseFading": ("Activity base is fading", "База активности ослабевает"),
    "insights.domain.activity.trend.inBalance": ("Training in balance", "Тренировки в балансе"),
    "insights.domain.activity.trend.baseBuilding": ("Activity base is building", "База активности формируется"),
    "insights.domain.activity.takeaway.rhythm": ("You maintained a repeatable training rhythm without a recovery cost.", "Вы поддерживали повторяемый тренировочный ритм без ущерба для восстановления."),
    "insights.domain.activity.takeaway.movementSoftened": ("Daily movement softened, which reduced the strength of the activity score.", "Ежедневное движение ослабло, что снизило силу показателя активности."),
    "insights.domain.activity.takeaway.loadFaster": ("Training load increased faster than recovery capacity.", "Тренировочная нагрузка выросла быстрее, чем способность к восстановлению."),
    "insights.domain.activity.takeaway.movementSupported": ("Daily movement supported training balance without adding strain.", "Ежедневное движение поддержало баланс тренировок без дополнительной нагрузки."),
    "insights.domain.activity.takeaway.matched": ("Workload stayed matched to readiness across the month.", "Нагрузка оставалась согласованной с готовностью в течение месяца."),
    "insights.domain.activity.focus.reduceVolume": ("Reduce weekly volume.", "Сократите недельный объём."),
    "insights.domain.activity.focus.increaseMovement": ("Increase easy daily movement.", "Увеличьте лёгкое ежедневное движение."),
    "insights.domain.activity.signal.consistency.label": ("Strong consistency", "Сильная стабильность"),
    "insights.domain.activity.signal.consistency.value": ("You maintained a repeatable training rhythm.", "Вы поддерживали повторяемый тренировочный ритм."),
    "insights.domain.activity.signal.load.label": ("Load in balance", "Нагрузка в балансе"),
    "insights.domain.activity.signal.load.increased": ("Workload increased without a recovery cost.", "Нагрузка выросла без ущерба для восстановления."),
    "insights.domain.activity.signal.load.controlled": ("Workload stayed controlled enough to support progress.", "Нагрузка оставалась достаточно контролируемой для поддержки прогресса."),
    "insights.domain.activity.signal.recovery.label": ("Recovery matched demand", "Восстановление соответствует нагрузке"),
    "insights.domain.activity.signal.recovery.noFatigue": ("No signs of accumulated fatigue.", "Нет признаков накопленной усталости."),
    "insights.domain.activity.signal.recovery.needsRoom": ("Recovery needs more room before the next progression.", "Восстановлению нужно больше запаса перед следующим прогрессом."),
    "insights.domain.activity.validation.strongDespiteMovement": ("Training stayed strong despite lower movement", "Тренировки оставались сильными несмотря на меньшее движение"),
    "insights.domain.activity.validation.rebuilding": ("Activity is rebuilding but needs consistency", "Активность восстанавливается, но нуждается в стабильности"),
    "insights.domain.activity.validation.strongTakeaway": ("Load remained sustainable while movement softened.", "Нагрузка оставалась устойчивой, пока движение ослабло."),
    "insights.domain.activity.validation.rebuildingTakeaway": ("Movement is improving but not yet stable.", "Движение улучшается, но ещё не стабильно."),
    "insights.domain.nutrition.trend.proteinOpportunity": ("Protein remains the opportunity", "Белок остаётся возможностью"),
    "insights.domain.nutrition.trend.supportsTraining": ("Nutrition supports training", "Питание поддерживает тренировки"),
    "insights.domain.nutrition.trend.hydrationImproving": ("Hydration is improving", "Гидратация улучшается"),
    "insights.domain.nutrition.trend.becomingConsistent": ("Nutrition is becoming consistent", "Питание становится стабильным"),
    "insights.domain.nutrition.trend.inBalance": ("Nutrition is in balance", "Питание в балансе"),
    "insights.domain.nutrition.takeaway.protein": ("Protein consistency is still the clearest nutrition opportunity.", "Стабильность белка — всё ещё самая явная возможность в питании."),
    "insights.domain.nutrition.takeaway.hydration": ("Hydration is moving toward the range that better supports recovery.", "Гидратация движется к диапазону, который лучше поддерживает восстановление."),
    "insights.domain.nutrition.takeaway.energy": ("Energy intake matched activity demand well enough to support training.", "Потребление энергии достаточно соответствовало нагрузке для поддержки тренировок."),
    "insights.domain.nutrition.takeaway.mealLogging": ("Meal logging is becoming more reliable but still limits confidence.", "Запись блюд становится надёжнее, но всё ещё ограничивает уверенность."),
    "insights.domain.nutrition.takeaway.strong": ("Nutrition is strong enough to support recovery and training.", "Питание достаточно сильное для поддержки восстановления и тренировок."),
    "insights.domain.nutrition.focus.increaseProtein": ("Increase protein intake.", "Увеличьте потребление белка."),
    "insights.domain.nutrition.focus.hydration": ("Improve hydration consistency.", "Улучшите стабильность гидратации."),
    "insights.domain.nutrition.focus.logWeek": ("Log one complete week.", "Запишите одну полную неделю."),
    "insights.domain.nutrition.signal.protein.label": ("Protein remains the opportunity", "Белок остаётся возможностью"),
    "insights.domain.nutrition.signal.protein.below": ("Protein consistency is still below demand.", "Стабильность белка всё ещё ниже потребности."),
    "insights.domain.nutrition.signal.protein.reliable": ("Protein is reliable enough to support adaptation.", "Белок достаточно стабилен для поддержки адаптации."),
    "insights.domain.nutrition.signal.quality.label": ("Meal quality improved", "Качество блюд улучшилось"),
    "insights.domain.nutrition.signal.quality.reliable": ("Nutrition became more reliable this month.", "Питание стало надёжнее в этом месяце."),
    "insights.domain.nutrition.signal.quality.moreMeals": ("More logged meals will make the pattern clearer.", "Больше записанных блюд сделает паттерн понятнее."),
    "insights.domain.nutrition.signal.recovery.label": ("Recovery support", "Поддержка восстановления"),
    "insights.domain.nutrition.signal.recovery.strong": ("Nutrition is strong enough to support training.", "Питание достаточно сильное для поддержки тренировок."),
    "insights.domain.nutrition.signal.recovery.limiter": ("Nutrition still has a limiter before harder training.", "Питание всё ещё имеет ограничитель перед более тяжёлыми тренировками."),
    "insights.domain.nutrition.validation.strongDespiteInputs": ("Nutrition stayed strong despite softer inputs", "Питание оставалось сильным несмотря на более слабые данные"),
    "insights.domain.nutrition.validation.improvingLimited": ("Nutrition is improving but still limited", "Питание улучшается, но всё ещё ограничено"),
    "insights.domain.nutrition.validation.strongTakeaway": ("Nutrition quality held while inputs softened.", "Качество питания сохранилось, пока данные ослабли."),
    "insights.domain.nutrition.validation.improvingTakeaway": ("Support is rising but still has a limiter.", "Поддержка растёт, но всё ещё имеет ограничитель."),
}


def make_entry(en: str, ru: str) -> dict:
    return {
        "extractionState": "manual",
        "localizations": {
            "en": {"stringUnit": {"state": "translated", "value": en}},
            "ru": {"stringUnit": {"state": "translated", "value": ru}},
        },
    }


def main() -> None:
    with XCSTRINGS.open(encoding="utf-8") as f:
        data = json.load(f)

    strings = data["strings"]
    added = 0
    skipped = 0
    for key, (en, ru) in TRANSLATIONS.items():
        if key in strings:
            skipped += 1
            continue
        strings[key] = make_entry(en, ru)
        added += 1

    with XCSTRINGS.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Added {added} keys, skipped {skipped} existing")
    print(f"Total keys in script: {len(TRANSLATIONS)}")


if __name__ == "__main__":
    main()
