#!/usr/bin/env python3
"""Curated Simplified Chinese for Coach Assistant / Feeling / core dialogue.

Merged into .coach_zh_hans_cache.json by generate_coach_chinese_overrides.py.
Natural, concise fitness-assistant tone — not literal EN calques.
"""

from __future__ import annotations

# Exact English keys as they appear in CoachBilingualText / bi() sources.
CURATED: dict[str, str] = {
    # Areas
    "Activity": "活动",
    "Nutrition": "营养",
    "Recovery": "恢复",
    # Feelings / chips
    "Okay": "还行",
    "Tired": "疲惫",
    "Energized": "精力充沛",
    "Low": "不太好",
    "Good": "很好",
    "Sleepy": "困倦",
    "Sore": "酸痛",
    "Stressed": "压力大",
    "Heavy legs": "腿很沉",
    "Mentally drained": "脑子很累",
    "Body feels heavy": "身体沉重",
    "Hard to focus": "很难集中注意力",
    # Openings
    "Good morning": "早上好",
    "Good afternoon": "下午好",
    "Good evening": "晚上好",
    "How are you feeling today?": "你今天感觉怎么样？",
    "How are you feeling now?": "你现在感觉怎么样？",
    "How are you feeling?": "你感觉怎么样？",
    "How’s your energy right now?": "你现在精力怎么样？",
    "How's your energy right now?": "你现在精力怎么样？",
    "Quick check-in. How’s your body feeling?": "快速确认一下。身体感觉如何？",
    "Quick check-in. How's your body feeling?": "快速确认一下。身体感觉如何？",
    "Another check-in. How’s energy right now?": "再确认一下。现在精力如何？",
    "Another check-in. How's energy right now?": "再确认一下。现在精力如何？",
    "What’s your body telling you now?": "身体现在在告诉你什么？",
    "What's your body telling you now?": "身体现在在告诉你什么？",
    "How are you feeling this time?": "这次感觉怎么样？",
    "What are you noticing most?": "你最明显的感觉是什么？",
    "What shall we start with?": "我们从哪里开始？",
    "What else do you want to look at?": "还想看什么？",
    "Got it — feeling tired.": "明白了——感觉有点累。",
    "Got it — not great today.": "明白了——今天状态不太好。",
    "Got it.": "好的。",
    "Good to hear.": "很高兴听到。",
    # Topic prompts
    "Want to look at sleep, training, or food?": "想看看睡眠、训练还是饮食？",
    "Shall we look at activity, nutrition, or recovery?": "要看活动、营养还是恢复？",
    "Activity, nutrition, or recovery?": "活动、营养还是恢复？",
    "Last 7 days": "近 7 天",
    "Last 7 nights": "近 7 晚",
    "Open Meals": "打开饮食",
    "Open Profile": "打开个人资料",
    "Review plan": "查看计划",
    "What’s left": "还剩多少",
    "What's left": "还剩多少",
    "Next meal": "下一餐",
    # Recovery / sleep
    "Sleep": "睡眠",
    "Deep sleep": "深睡",
    "Resting heart rate": "静息心率",
    "Heart rate variability": "心率变异性（HRV）",
    "HRV": "HRV",
    "Your sleep last night looks shorter than usual.": "昨晚睡眠比平时短一些。",
    "Your sleep last night looks solid.": "昨晚睡眠看起来不错。",
    "I don’t have enough sleep data yet.": "我还没有足够的睡眠数据。",
    "I don't have enough sleep data yet.": "我还没有足够的睡眠数据。",
    "Deep sleep looks a bit light.": "深睡有点偏少。",
    "HRV is a bit lower than your recent baseline.": "HRV 比你最近的基线略低。",
    "Resting heart rate is a bit higher than usual.": "静息心率比平时略高。",
    "Recovery signals look steady.": "恢复信号看起来平稳。",
    "Recovery looks protected — keep today easier.": "恢复状态需要呵护——今天尽量轻松一些。",
    # Activity
    "You already moved today.": "你今天已经活动过了。",
    "No sessions logged yet today.": "今天还没有记录训练。",
    "Load over the last 7 days looks manageable.": "近 7 天的负荷看起来可控。",
    "Load over the last 7 days looks higher than usual.": "近 7 天的负荷比平时高。",
    "I don’t have enough activity data for a fair look.": "活动数据还不够，暂时不好比较。",
    "I don't have enough activity data for a fair look.": "活动数据还不够，暂时不好比较。",
    "Compared with yesterday, today looks lighter.": "和昨天比，今天看起来更轻松。",
    "Compared with yesterday, today looks busier.": "和昨天比，今天看起来更忙。",
    # Nutrition
    "Protein is tracking well so far.": "目前蛋白质摄入不错。",
    "You’re still short on protein for today.": "今天蛋白质还差一点。",
    "You're still short on protein for today.": "今天蛋白质还差一点。",
    "Calories look on track.": "热量目前在目标附近。",
    "There’s still room before your calorie target.": "离热量目标还有一些空间。",
    "There's still room before your calorie target.": "离热量目标还有一些空间。",
    "I don’t see meals logged yet today.": "今天还没有看到饮食记录。",
    "I don't see meals logged yet today.": "今天还没有看到饮食记录。",
    "Water looks low so far.": "目前饮水量偏低。",
    # Completions
    "That’s enough for now.": "今天先到这里。",
    "That's enough for now.": "今天先到这里。",
    "Anytime — I’m here when you want another look.": "随时可以再来，想看的时候我都在。",
    "Anytime — I'm here when you want another look.": "随时可以再来，想看的时候我都在。",
    "Nice work checking in.": "来确认一下状态，很好。",
    # Gates / missing data
    "Health data isn’t available yet.": "健康数据还不可用。",
    "Health data isn't available yet.": "健康数据还不可用。",
    "Allow Health access to personalize this.": "允许访问健康数据后，我可以更贴合你。",
    "Want a quick look anyway?": "还是想先快速看一眼？",
    "We can still talk about what you noticed.": "我们还是可以聊聊你注意到的情况。",
    # Chrome / badges
    "IMPORTANT": "重要",
    "Breath work": "呼吸练习",
    "Yoga": "瑜伽",
    "Yoga time": "瑜伽时间",
    "Yoga session": "瑜伽训练",
    "Stretching": "拉伸",
    "Stretch time": "拉伸时间",
    "Stretch session": "拉伸训练",
    "Recovery time": "恢复时间",
    "Keep it light": "保持轻松",
    "Ease the legs": "放松双腿",
    "Wind down": "放慢节奏",
    "Save it for tomorrow": "留给明天",
    "Recovery day": "恢复日",
    "Leave something": "留点余力",
    "Hold your pace": "保持节奏",
    "Don't overheat": "别过热",
    "Soft reset": "轻柔放松",
    "Today's plan": "今日计划",
    "Ready": "状态良好",
    "Steady": "平稳",
    "Protect": "保护",
    "Recover": "恢复",
    "Yes": "是",
    "No": "否",
    "Done": "完成",
    "Today": "今天",
    "Last night": "昨晚",
    "A few days": "这几天",
    "Plan vs logged": "计划与记录",
    "Changed plans": "计划有变",
    "What else do you want to look at?": "还想看什么？",
    "What shall we start with?": "我们从哪里开始？",
    "What would help with food today?": "今天饮食上想看哪一块？",
    "What’s left": "还剩多少",
    "What's left": "还剩多少",
    "Next meal": "下一餐",
    "Is this mostly about last night’s sleep, or has it been building for a few days?": "主要是昨晚睡眠，还是这几天一直这样？",
    "Is this mostly about last night's sleep, or has it been building for a few days?": "主要是昨晚睡眠，还是这几天一直这样？",
    "What should we look at in your activity log?": "想看活动记录里的哪一块？",
    "Your recovery is below your usual range today.": "今天恢复低于你平时的范围。",
    "You slept less than usual last night.": "昨晚睡得比平时少。",
    "Your recovery looks in good shape for you today.": "今天你的恢复看起来不错。",
    "Your sleep and recovery look close to usual.": "睡眠和恢复都接近平时。",
    "Recent sleep, HRV, or resting heart rate readings aren’t available yet — they may still be syncing, or weren’t recorded.": "近期睡眠、HRV 或静息心率数据还不可用——可能仍在同步，或尚未记录。",
    "Recent sleep, HRV, or resting heart rate readings aren't available yet — they may still be syncing, or weren't recorded.": "近期睡眠、HRV 或静息心率数据还不可用——可能仍在同步，或尚未记录。",
    "There isn’t enough recent sleep, HRV, or resting heart rate data available to personalize this yet.": "近期睡眠、HRV 或静息心率数据还不够，暂时无法更贴合你。",
    "There isn't enough recent sleep, HRV, or resting heart rate data available to personalize this yet.": "近期睡眠、HRV 或静息心率数据还不够，暂时无法更贴合你。",
}
